mod-kb-ebsco/mod-kb-ebsco.postman_collection.json

Multiple fixes went into mod-kb-ebsco this week as a result of which API tests started to fail. This PR fixes the tests.
Issues in mod-kb-ebsco that were fixed that led to these failures are:
- https://issues.folio.org/browse/UIEH-495
- https://issues.folio.org/browse/UIEH-466
- https://issues.folio.org/browse/UIEH-470
- https://issues.folio.org/browse/UIEH-427

Fix mod-kb-ebsco tests

---

mod-kb-ebsco/mod-kb-ebsco.postman_collection.json

Certain mod-kb-ebsco API tests started to fail after we changed the approach of validating updates to managed resources when the user passes fields of custom resources. Reason for why we had to change the approach is mentioned here: https://github.com/folio-org/mod-kb-ebsco/pull/195
This PR modifies the API tests to align with the above mentioned fix in mod-kb-ebsco.

Update mod-kb-ebsco API tests

---

mod-gobi/mod-gobi.postman_collection.json

Created **validate** tests for 204, 403, 401 cases. 
Will add more tests, especially 403 - forbidden, insufficient privileges - when there's an agreement of how to go about setting up the test. 
I was going to add tests for **orders** but kept getting back 504, might be related to Okapi failures, pausing on this effort for now. There's a JIRA for writing **orders** API tests so this work could be done there.

add mod-gobi /validate tests

---

mod-kb-ebsco/mod-kb-ebsco.postman_collection.json

Mod-kb-ebsco has been updated to use the same location for KB credentials as it used by mod-codex-ekb. https://issues.folio.org/browse/MODKBEBSCO-6 has details of changes.
Due to this change, update mod-kb-ebsco tests:
(1)Update setup configuration to look for configuration settings in new location which is shared with mod-codex-ekb:
`GET /configurations/entries?query=(module==EKB and configName==api_access and code==kb.ebsco.url)`
`GET /configurations/entries?query=(module==EKB and configName==api_access and code==kb.ebsco.customerId)`
`configurations/entries?query=(module==EKB and configName==api_access and code==kb.ebsco.apiKey)`
(2) Update tear-down configuration to use new locations for configuration as well

Update mod-kb-ebsco tests due to new location for KB configuration

---

mod-codex-ekb/mod-codex-ekb.postman_collection.json

mod-codex-ekb build in FSE devQA is failing due to failing tests in mod-codex-ekb. One of the existing tests was searching for `title=zaz*` and expecting results to be empty but RM API returns a title in results for that search string. Updated the search string to `title=guz*` that returns 0 results as of today to make these tests pass. I am not sure if we should have tests of this sort in the long run.

Update mod-codex-ekb tests to suit breaking changes

---

mod-codex-ekb/mod-codex-ekb.postman_collection.json

Two issues have been addressed in mod-codex-ekb:
https://issues.folio.org/browse/MODCXEKB-59
https://issues.folio.org/browse/MODCXEKB-64
The implementation/fixes for the above resulted in 3 failing tests: 
1. Tests that search for a non-existing title(Eg: title=guz*) and expect results to be 0 but after implementation of https://issues.folio.org/browse/MODCXEKB-64, this test will no longer pass as we'll always get results with wildcard characters. Change it to something like (Eg: id=123) so that it'll always consistently return 0 results. id here is isxn which can never be of a format like `123`
2. Another test was failing because its expecting a 500 response but after https://issues.folio.org/browse/MODCXEKB-59 is fixed, it now returns a 400 which is expected response. 
This PR fixes the …

Update failing API tests in mod-codex-ekb

---

mod-users/mod-users.postman_collection.json

The latest build of mod-users requires the "id" field to be an actual UUID, whereas older builds would take any string since this is ignored as it is written to the DB and a new UUID is returned. For some reason, "id" is a required field in the user schema which means that the client needs to send something and the schema does not enforce UUID format via a pattern. The documentation does indicate "id" must be a UUID. It appears that a UUID without the '-' characters is accepted, as the example in the API doc shows. Anyway, this test works now.

Correct malformed JSON

---

mod-inventory-storage/mod-inventory-storage-location.postman_collection.json

The locations managed by this API require a new property, `primaryServicePoint`. However, there is a runtime dependency on the new `servicePointIds` array to contain the `primaryServicePoint`, so these needed to be added when using the locations API.
Also added `/service-points` API tests in order to have a service point for the locations API to use.

Fix mod-inventory-storage locations API tests

---

mod-login/mod-login.postman_collection.json

mod-login module build is failing in our devQA Jenkins due to a failing test. Test is for a POST request to /authn/login without a tenant header which probably was returning 403 status at some point which has now been changed to return a 400 status code. 
Per https://s3.amazonaws.com/foliodocs/api/mod-login/login.html#authn_login_post, we do not see a 403 mentioned and if we tweak the tests to expect a 400 response, all tests pass. This PR addresses that change.

Adjust mod-login tests per schema changes

---

mod-users/mod-users.postman_collection.json

mod-users build fails in our Jenkins pipeline. Reason is that API tests are trying to get schemas from master branch of https://github.com/folio-org/raml/tree/ which does not exist anymore. We either have to get them from https://github.com/folio-org/raml/tree/raml0.8/schemas or https://github.com/folio-org/raml/tree/raml1.0/schemas for these tests to pass. 
Getting them from https://github.com/folio-org/raml/tree/raml0.8/schemas because https://github.com/folio-org/raml/tree/raml1.0/schemas does not have mod-users related schemas in it yet. This fixes all the API tests.

Adjust mod-users tests to get schemas from RAML0.8 branch

---

mod-login/mod-login.postman_collection.json

Earlier, we made this change because mod-login changed due to a checkin but they reverted that change of theirs, so reverting this test change

Revert change made to api-tests for mod-login

---

mod-kb-ebsco/mod-kb-ebsco.postman_collection.json

API tests of mod-kb-ebsco are failing because in a particular test of getting a custom package, we are checking that the first package's name contains "package" using this snippet of JS code - `pm.expect(firstRecord.attributes.name).to.include('package');` and the results themselves have packages created of the format `Custom Package Postman 1515004981` and JS include does not check for strings ignoring case. Modifying the test to check for "Package" case sensitively fixes it. 
I tried to see if something changed recently with "include" in chai.js but no, it seems more like the way Postman is auto-generating those package names.

Update name for case sensitivity in mod-kb-ebsco

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-88 and https://issues.folio.org/browse/MODKBEKBJ-89 -- add test for Configuration GET and PUT Requests
- Added new folder for configuration tests
- Updated setup configuration section to save configuration so that it can be used in tests
- Added Positive Test for GET Configuration
- Added Placeholder for Negative Tests with notes on outstanding cache issue (Reference Jira ticket)
- Added Positive and Negative Tests for PUT configuration with notes on error issues (reference Jira tickets)
Outstanding Issues (to be addressed in separate PRs)
- Unable to test GET Configuration Negative cases due to caching -- added ticket to add a way to invalidate cache from api
https://issues.folio.org/browse/MODKBEKBJ-103 
- Encountered issues with permissions …

MODKBEKBJ-88 - MOD-KB-EBSCO-JAVA Configuration GET/PUT tests

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-61 we want to have API Tests for GET /eholdings/providers/{providerId}/packages endpoint

MODKBEKBJ-61 - API Tests GET /eholdings/providers/{providerId}/packages endpoint

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-65 we want to have API tests for POST `/eholdings/packages `endpoint

MODKBEKBJ-65 - API Tests POST /eholdings/packages endpoint

---

mod-orders/mod-orders.postman_collection.json

* Per [MODORDERS-76](https://issues.folio.org/browse/MODORDERS-76) we want to have API Tests for [POST /orders/{id}/lines endpoint](https://s3.amazonaws.com/foliodocs/api/mod-orders/order.html#orders__id__lines_post)
* Per [MODORDERS-78](https://issues.folio.org/browse/MODORDERS-78) we want to have API Tests for [GET /orders/{id}/lines/{id} endpoint](https://s3.amazonaws.com/foliodocs/api/mod-orders/order.html#orders__id__lines__lineid__get)
* Per [MODORDERS-79](https://issues.folio.org/browse/MODORDERS-79) we want to have API Tests for [DELETE /orders/{id}/lines/{id} endpoint](https://s3.amazonaws.com/foliodocs/api/mod-orders/order.html#orders__id__lines__lineid__delete)
* Added API tests to the mod-orders postman collection to check positive and negative scenarios. For positive scenario …

API tests for POST /orders/id/lines and GET, DELETE /orders/id/lines/id endpoints

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-72 we want to have API Tests for GET /eholdings/packages/{packageId}/resources endpoint

MODKBEKBJ-72 - API Tests GET /eholdings/packages/{packageId}/resources endpoint

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-70 we want to have API Tests for PUT `/eholdings/packages/{packageId}` endpoint

MODKBEKBJ-70 - API Tests PUT /eholdings/packages/{packageId} endpoint

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-71 we want to have API Tests for  DELETE `/eholdings/packages/{packageId}` endpoint

MODKBEKBJ-71 - API Tests DELETE /eholdings/packages/{packageId} endpoint

---

mod-orders/mod-orders.postman_collection.json

- Add few positive (update line with empty content, update empty line with meaningful content) and negative (422 validation errors, 500 server side error) tests for `PUT` order line operation
- The `utils` have been updated:
- The `alert`, `claim`, `fund_distribution`, `renewal` and `reporting_code` schemas are now enabled to validate PO Line content
- `validatePoLines(order, expectedCount)` function added to validate presence of the PO lines of expected quantity and its sub-object elements
- `preparePoLine(poLine)` function added to update sub-objects of the PO Line removing ids and adding some missing data
- `prepareOrder(order)` function added to update PO json removing ids and updating PO lines
- `unsetTestVariables()` function added to clean up all the variables defined in tests
- …

MODORDERS-77 PUT order line

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-69 we want to have API Tests for GET /eholdings/packages/{packageId}?include=provider endpoint that are not in https://github.com/folio-org/folio-api-tests/blob/master/mod-kb-ebsco/mod-kb-ebsco.postman_collection.json

MODKBEKBJ-69 - API Tests GET /eholdings/packages/{packageId}?include=provider

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-81 we want to have API Tests for PUT /eholdings/resources/{resourceId} endpoint
- this pr should be merged only after https://github.com/folio-org/mod-kb-ebsco-java/pull/85 id done. Without it a test "/resources PUT update custom resource missing identifier id" will fail

MODKBEKBJ-81 - API Tests PUT /eholdings/resources/{resourceId} endpoint

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-135](https://issues.folio.org/browse/MODORDERS-135) Update Physical schema: Add expectedReceiptDate
Test to verify expected receipt date in the PO Line
* Pre-request
* Get PO Line by id
* Add `physical` sub-object to PO line with `expectedReceiptDate` property
* Request
* Send PUT order line request
* Tests
* Verify `204` code
* Get PO Line by id and verify that PO Line has expected receipt date

MODORDERS-135 Update Physical schema: Add expectedReceiptDate

---

mod-orders/README.md
mod-orders/mod-orders.postman_collection.json

Updating API Tests to verify changes for [MODORDERS-130](https://issues.folio.org/browse/MODORDERS-130), [MODORDERS-145](https://issues.folio.org/browse/MODORDERS-145) and [MODORDERS-150](https://issues.folio.org/browse/MODORDERS-150)
- The Negative Tests restructured
- MODORDERS-145:
- Updated: `Positive tests` -> `Empty Order` -> `Create empty order` - added test to verify that created order has `Pending` workflow status if it was not specified upon order creation
- Added: `Negative Tests` -> `Lines` -> `Verify PO Line required properties` -> `Create line - no source - 422` to verify validation exception if no source provided
- MODORDERS-150: Added: `Positive tests` -> `Empty Order` -> `Update order with new po_number` to verify that order can be updated if upon order creation the …

Update tests for MODORDERS-130, MODORDERS-145 and MODORDERS-150

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-155 we want to use modifications made for RMB module related to /_/jsonSchemas endpoint.
- used /_/jsonSchemas endpoint to get a list of JSON schemas available for module
- updated schema download script to retrieve a list of JSON schemas and download them at once
- removed requests for fetching schemas associated with a separate endpoint
- changed validation of JSON API schema in case of negative test cases to use mod-kb-ebsco-java module JSON error schemas.
Run API tests on local environment against testing-backend using Postman collection runner and newnan.

MODKBEKBJ-155 - Refactor Postman API test

---

mod-orders/mod-orders.postman_collection.json

API tests are failing after splitting PO sub-objects `order_format` and `receipt_status` into separate schemas due PR https://github.com/folio-org/acq-models/pull/98
Adding schemas `order_format.json` and `receipt_status.json` to "Load schemas for validation" folder and update schemas loading script.

MODORDSTOR-59 added missing schemas for validation

---

mod-orders/mod-orders.postman_collection.json

Fix API tests after moving productIdType from details.json to separate file in common folder and moving schemas for composite purchase order and composite poLine to mod-orders folder due PR [folio-org/acq-models#99](https://github.com/folio-org/acq-models/pull/99)
- Adding schema `product_id_type.json` to "Load schemas for validation" folder and update schemas loading script.
- updated requests paths for retrieving  composite_purchase_order.json and composite_po_line.json

MODINVOSTO-2 Define APIs

---

edge-oai-pmh/edge-oai-pmh.postman_collection.json

Changing apikey as a result of migration to edge-common-2.0.0 and edge-oai-pmh updating

EDGOAIPMH-28 - Upgrade to edge-common v2.0.0

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-175](https://issues.folio.org/browse/MODORDERS-175) Add ability to move a received piece back to "Expected"
The following requests added:
- `Revert all received pieces for P/E Mix line` 
also verifies that PO Line's receipt status changed from `Fully Received` to `Awaiting Receipt`  
- `Revert all received pieces for physical line` 
also verifies that PO Line's receipt status changed from `Partially Received` to `Awaiting Receipt`
- `Revert 2 received pieces for electronic line (without items in Inventory)` 
also verifies that PO Line's receipt status changed from `Fully Received` to `Partially Received`
- `Revert 1 received piece for electronic line (with items in Inventory)` 
also verifies that PO Line's receipt status changed from `Fully Received` to `Partially Received`

MODORDERS-175 Add ability to move a received piece back to "Expected"

---

mod-orders/mod-orders.postman_collection.json

- MODORDERS-168 Update tests to support schema changes
- MODORDERS-170 Get active vendor to use in tests
New request added to get active vendor's `id` to use in further requests: Setup/Prepare vendors/Get active vendor

Updating mod-orders API tests after schema refactoring

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-184](https://issues.folio.org/browse/MODORDERS-184) update API Tests to check GET /orders/receiving-history returns properties defined in [folio-org/acq-models#100](https://github.com/folio-org/acq-models/pull/100)
The following requests added:
- `Create Open order for receiving history test` 
creates order based on po_listed_print_monograph.json with defined property  `checkinItems` for poLines
- `Delete Open order for receiving history test`
Updated  `Get receiving history for Open Order` to check that receivingHistory response contains expected fields

MODORDERS-184 Receiving history: updates to support check-in flow

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-202, we were seeing various API test failures in mod-kb-ebsco-java when run in Ebsco's CI/CD pipeline. While most of the failures have been addressed in this https://github.com/folio-org/folio-api-tests/pull/118, there were still a few assertions failing. 
Fix those in this PR. 
Newman output when run against FSE env:
[output.txt](https://github.com/folio-org/folio-api-tests/files/2989708/output.txt)

MODKBEKBJ-202: Update api tests to avoid failures in FSE

---

mod-login/mod-login.postman_collection.json

mod-login API tests are failing for release 5.1 and 5.0 in EBSCO's CI/CD Pipeline
The main reasons are due to status code changes -- 422 is now returned when 400 was previously -  additionally a 400 code is returned instead of 403.
Added below ticket to confirm status code changes are intentional. Temporarily updated the API tests to reflect new status codes so that module tests pass and it can be deployed. Noted below Jira ticket in API tests as reference
https://issues.folio.org/browse/MODLOGIN-107

Update mod-login tests -- reflect current status codes

---

mod-inventory/mod-inventory.postman_collection.json
mod-login/mod-login.postman_collection.json

mod-inventory tests are failing in EBSCO's CI/CD Pipeline -- this PR corrects 2 failing tests
1.  AssertionError  'Location'header is present                           
expected response to have header with key 'Location'  
at assertion:1 in test-script                         
inside "items / /inventory/items"                     
2.  AssertionError  Response must contain the expected number of records  
expected 10 to equal 20                               
at assertion:2 in test-script                         
inside "instances / /inventory/instances - limit 100" 
(1) Missing Location header in /inventory/items POST -- response -- created Jira issue to confirm this change is intended -- https://issues.folio.org/browse/MODINV-111 - commented check pending response
(2) Issues was due to …

Update mod-inventory tests and mod-login -- comments only

---

mod-gobi/mod-gobi.postman_collection.json

Fixing clean up requests
At the moment cleanup requests fail with following error:
`vendorId` is set as environment variable after vendor is created by `/vendor-storage/vendors  - POST GOBI Vendor` request from `Test Setup` folder
To fix clean up requests the content of `Pre-request Script` section is removed for `/vendor-storage/vendors - Delete created Vendor` and `Order with overrides` requests from `Cleanup` folder

MODGOBI-58 Release 1.3.0 - correcting clean up requests

---

edge-oai-pmh/edge-oai-pmh.postman_collection.json

Several minor issues were found while running these API tests in one of EBSCO's hosted environments.
* the Access Denied tests (which expect 403), were failing because the key being sent was invalid (which results in a 401).
* the resumptionToken tests were failing because an extra `/` was making it into the URI after the port, e.g. `host:8081//oai/...`  
* Specify an API key which is technically valid, yet almost certain to cause access denied: ```java -jar edge-common-api-key-utils.jar -p eyJzIjoiQUJDREVGR0hJSiIsInQiOiJib2d1cyIsInUiOiJib2d1cyJ9
Salt: ABCDEFGHIJ
Tenant ID: bogus
Username: bogus```
* when building the URI for requests w/ resumption tokens (in the utils), remove/omit the extra slash

fix access denied tests and resumptionTokens

---

mod-gobi/mod-gobi.postman_collection.json

While testing the GOBI API tests it was observed that mod-orders is timing out with 504, if a vendor_status field is not present while placing an order. 
Though https://issues.folio.org/browse/MODORDERS-203 was created to address the issue. 
Adding the field in order to get the API tests working
##TODO

Adding vendor_status while creating a GOBI vendor

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-195 - To add material type to each resource separately
- Added a new test in setup to fetch the existing material type from /material-types API, so that tests can run and create items independent of environment
- Changed all test cases to utilize the material type obtained from the API
- Changed validations relating to the required fields
ADDITIONAL CHANGES
Fixed issues with calculating inventory items quantity for "Other"
Verified against folio-testing

MODORDERS-195- Add material types to each resource

---

mod-organizations-storage/mod-organizations-storage.postman_collection.json

Updating test to use latest endpoint names introduced by https://github.com/folio-org/mod-organizations-storage/pull/9
`organization-storage/organizations` -> `organizations-storage/organizations`

MODORGS-5 Create API Test Skeleton - updating endpoint name

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-208
Add API tests for [PR#139](https://github.com/folio-org/mod-orders/pull/139) and fix failing tests as a result of this change.
https://issues.folio.org/browse/MODORDERS-208

API tests for MODORDERS-208 - Make vendor UUID required

---

mod-orders/mod-orders.postman_collection.json

- added utils.validatePaymentStatus method
- Added checks of payment statuses for "Pending->Open" order transition for cases: 
- poLines payment status is "Pending" and should change
- poLines payment status is not "Pending" and shouldn't be changed
Since the tests were falling due to the changes, added `purchaseOrder.vendor` to requests where it's required
Collection run on folio-testing

MODORDERS-211 Order Status: Align POL Payment and Receipt status withPO Status when opening order

---

mod-notes/mod-notes.postman_collection.json

https://issues.folio.org/browse/MODNOTES-81
Creating API tests for note-type by id endpoint.

MODNOTES-81 API Tests for GET /note-types/{typeId}

---

mod-notes/mod-notes.postman_collection.json

https://issues.folio.org/browse/MODNOTES-80
Creating API tests for note-type by id endpoint.

MODNOTES-80 API Tests for POST /note-types

---

mod-notes/mod-notes.postman_collection.json

https://issues.folio.org/browse/MODNOTES-82
Creating API tests for note-type endpoint.

MODNOTES-82 API Tests for PUT /note-types/{typeId}

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-205](https://issues.folio.org/browse/MODORDERS-205) Verify expected piece format
- new `utils.validatePieceRecords(poLine, arePiecesCreated)` function is added to validate if expected quantity of piece records created with valid content. The function sends `GET /orders-storage/pieces` by PO Line id and verifies that no piece records exist if order is `Pending` or expected quantity created depending on PO Line data
- `utils.calculateExpectedPiecesQuantity(poLine, pieceFormat)` function is updated. Depending on `pieceFormat` it calculates expected piece records quantity
- `utils.validatePoLines(..)` function now also calls `utils.validatePieceRecords(..)`. As a result some of "get piece records" requests are removed because they are replaced by `validatePieceRecords` function

MODORDERS-205 Verify expected piece format

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-136](https://issues.folio.org/browse/MODORDERS-136) update API tests after adding new required fields
- updated "Create empty order with missing vendor UUID" request to verify `orderType` in addition to `vendor`
- updated "Create line - no source - 422" to verify all required field for poLine
- `utils.validatePoLineWithMinimalContent (poLine)` function is updated.
- `utils.buildOrderWithMinContent(..)` function now create order  with `vendor ` and `orderType`.

MODORDERS-136 Define required fields in the schemas

---

mod-orders/mod-orders.postman_collection.json

Add new test cases to cover checkin flow
- Added new util methods to create pieces and items as  they are not created by mod-orders during check in flow 
- Added new tests to cover scenarios 
1) for checkin without items required in inventory(pieces will be created in a pre request step)
2) checkin with items in inventory(pieces and items are created in pre-request step )
3) revert checkin of pieces and also verifying that the item status and piece status are also reverted in inventory
4) failure scenario which throws an error if a piece is tried to checkin again
Additional changes
1) Changed few util methods to cover scenarios for check-in where there can be holdings without items, and cleaning those records as well

MODORDERS-207 - Adding cases for checkin

---

mod-gobi/mod-gobi.postman_collection.json

Changed the tests to point to mod-organization-storage for vendors
**Additional Changes**
Added a util function to build the Okapi URL
Tested it on folio-testing

MODGOBI-67

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-25](https://issues.folio.org/browse/MODINVOICE-25) Use Json API for loading module schemas
- Load all schemas required for validation using GET /_/jsonSchemas API
- Create an invoice to verify that validation against schema approach works fine
- Delete created invoice
note: Since invoice APIs are not ready i used using mod-invoice-storage APIs. Must be replaced when the mod-invoice API is ready.
Collection run on local vagrant box

MODINVOICE-25 Use Json API for loading module schemas

---

mod-notes/mod-notes.postman_collection.json

We refactored notes to be domain specific as part of https://issues.folio.org/browse/MODNOTES-89 and https://issues.folio.org/browse/MODNOTES-90. Update API tests accordingly. 
Also, noticed few unrelated tests were failing as well. Fixed those too.

MODNOTES-91: Update tests mod notes

---

mod-orders/README.md
mod-orders/mod-orders.postman_collection.json

Positive Tests:
- `Close orders updating payment status of each PO Line` folder contains requests which update PO Lines' payment statuses of `Open` orders so the system should close the order eventually.
- Test example
- Functions which update PO Line's payment status
- `Check closed orders and re-open` folder contains sets of requests:
1. Get orders and verify that their workflow status is `Closed`. If this is `true`, modify one of PO Line's payment status so the order becomes `Open` eventually.
- Test example
2. Roll back one of received piece so the order becomes `Open` eventually.
3. Verify that orders were successfully re-opened by operations described above.
- Unused collection variables are deleted
New requests:
Local collection run

MODORDERS-218 adjust order status based on poLine's statuses

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-226 - API Tests for mod-kb-ebsco-java are failing 
The following 2 tests are failing since the package that they are testing for got deleted by a previous test
- Delete custom package created in post again
- Delete tags for another test package
Both tests are expecting a package defined by environment variable - `custom-package-id-created-in-post-again`
After research found that package `custom-package-id-created-in-post-again` is being deleted by another test
`update custom package with isSelected false should delete it`
https://github.com/folio-org/folio-api-tests/pull/125/files
Removed cleanup script tests since they are no longer necessary with added test

MODKBEKBJ-226 - Correct mod-kb-ebsco-java tests

---

mod-invoice/mod-invoice.postman_collection.json

**Purpose:**
API test for:
https://issues.folio.org/browse/MODINVOICE-21
**Approach:**
- Test invoice-line creation
- Validate fields against invoice_line schema
- Clean up
**Verification:**
Verified in - `folio-testing-okapi.aws.indexdata.com`

MODINVOICE-21 - API tests for POST invoice-lines

---

mod-permissions/mod-permissions.postman_collection.json

mod-permissions API tests started failing with Q2.1 release.
Corrected below 2 failing tests:
(1) Invalid user id returns a 400 error
(2)Missing Id returns a 422 error
Also update name from `mod-permssions copy` to `mod-permissions`
Changes show some formatting difference as well as removal of GET body. 
These were done by Postman (no explicit updates)
```
1.  AssertionError  Status is 500                                                               
expected response to have status code 500 but got 400                       
at assertion:0 in test-script                                               
inside "permissions / /perms/users/{{newpermissionuserid}}/permissions 500" 
2.  AssertionError  Status is 500                                                               
expected …
```

Correct mod-permissions Q2.1 test failures

---

mod-inventory-storage/mod-inventory-storage.postman_collection.json

The following API tests were failing after Q2.1 release:                                             
1.  AssertionError  Status is 500 - bad id                                    
expected response to have status code 500 but got 404     
at assertion:0 in test-script                             
inside "service-point / /service-points - get/{id} 500"   
2.  AssertionError  Response must be valid and have an error message          
expected false to be true                                 
at assertion:1 in test-script                             
inside "service-point / /service-points - get/{id} 500"   
3.  AssertionError  Status is 500 - bad Id                                    
expected response to have status code 500 but got 404     
at assertion:0 in test-script …

Update service points tests(mod-inventory-storage)

---

mod-invoice/mod-invoice.postman_collection.json

API tests for 
https://issues.folio.org/browse/MODINVOICE-30 -- PUT /invoice/invoice-lines/id
https://issues.folio.org/browse/MODINVOICE-41-- GET /voucher/vouchers/id
GET Vouchers
As Voucher does not have POST endpoint, creating the voucher using the storage endpoint
Also added the POST storage endpoint permission to the limited user permission
Added positive and negative cases
PUT Invoice lines
The positive and negative tests for updating invoice lines
tested on folio-testing
INVOICE-LINES
VOUCHERS

MODINVOICE-30- & MODINVOICE-41

---

mod-orders/README.md
mod-orders/mod-orders.postman_collection.json

- [MODORDERS-239](https://issues.folio.org/browse/MODORDERS-239) Make `instance-type` configurable
- [MODORDERS-240](https://issues.folio.org/browse/MODORDERS-240) Make `instance-status` configurable
- [MODORDERS-241](https://issues.folio.org/browse/MODORDERS-241) Make `loan-type` configurable
Variable | Initial Value | Description  
--- | --- | --- 
`inventory-instanceTypeCode` | ordersApiTestsInstanceTypeCode | Inventory instance type code which is going to be used for instance creation when order transits to `Open` status
`inventory-instanceStatusCode` | ordersApiTestsInstanceStatusCode | Inventory instance status code which is going to be used for instance creation when order transits to `Open` status
`inventory-loanTypeName` | ordersApiTestsLoanTypeName | Inventory loan type name …

Orders: make required inventory types configurable

---

mod-orders/mod-orders.postman_collection.json

- added negative tests to verify that the correct errors is returned
- added a request to the cleanup section that will delete the created inventory records (instances, holdings, items) by `identifierTypeId` from Setup/Prepare inventory types/Get or create Identifier Type request
Collection run on folio-testing:

MODORDERS-230/MODORDERS-232 Inappropriate error response on missing inventory records

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

The following tests were failing in FSE: 
packages / PUT package by packageId / Custom Package / Positive / update custom package
packages / PUT package by packageId / Custom Package / Positive / update custom package with empty tagList
While issuing a PUT request, we are giving the package a constant name all the time and since that package already exists, we are getting back a 400 response from RM API. Instead of updating the package name with a constant name all the time, use the name with a uuid.

MODKBEKBJ-243: Update package api tests

---

mod-invoice/mod-invoice.postman_collection.json

**Purpose:**
https://issues.folio.org/browse/MODINVOICE-48
**Approach:**
- One positive test to set voucher number start value
- One negative test to verify that the voucher number start value cannot be negative
**NOTE:**
To run all tests successfully, need changes from https://github.com/folio-org/folio-api-tests/pull/206 So probably a better idea to merge #206 first.
**Verified on folio-testing:**

API test for MODINVOICE-48 POST /voucher/voucher-number/start/<val>

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDSTOR-79
https://issues.folio.org/browse/MODORDSTOR-79
* Removed script that deletes pieces associated with PO and POLines 
* Added script to verify that all associated pieces are deleted
verifyAllPieceRecordsDeleted

MODORDSTOR-79 Remove associated piece records when removing POLine

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-257](https://issues.folio.org/browse/MODORDERS-257) Implement PUT and DELETE /orders/pieces/id
[MODORDERS-252](https://issues.folio.org/browse/MODORDERS-252) Make product id type to be uuid
- Positive and Negative tests for `POST`, `PUT` and `DELETE` piece by id
- New collection level variable `inventory-identifierTypeName` holds inventory identifier type name to create orders API Tests specific identifier
- While creating order, set productIdType to `identifierTypeId` environment variable value.
Verified in folio/testing local vagrant box:

API tests for MODORDERS-252(PUT DEL piece/id) and MODORDERS-257(product id type to be uuid)

---

mod-notes/mod-notes.postman_collection.json

After release of mod-notes, we observed 1 failing test -- noted in https://issues.folio.org/browse/MODNOTES-108
The test fails due to the fact that 16 notes are returned in the results -- the result list returns 10 notes.
There are two checks for notes. First element check and last element check.
Screen attached
For testing sort pretty enough the first element check. So I have deleted last element check.
Attached -- run against

MODNOTES-108 Failing API tests

---

mod-codex-mux/mod-codex-mux.postman_collection.json

Per https://issues.folio.org/browse/MODCXMUX-52 -- we are seeing an api test failure on MUX release.
Correct API test to check for body which includes the indicated text
"No suitable module found for path /codex-packages/"
Since text now includes tenant information
'No suitable module found for path /codex-packages/ for tenant fs00000000'

MODCXMUX-52: Correct mux text to check for body text contains

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-243](https://issues.folio.org/browse/MODORDERS-243) Create encumbrance upon order transition to "Open"
- Setup: Create test ledger and fund
- Utility functions:
- validateEncumbranceRecords(poLine, orderStatus) - checks how many encumbrances have been created based on POL's fundDistribution count. The function is called by `utils.validatePoLines`
- deleteEncumbranceRecords(poLine) - deletes all the encumbrance records associated with PO Line id
- Negative test: Encumbrance creation failure
- Cleanup:
- Delete Pending order (encumbrance creation failure)
- 2 requests to delete test fund and ledger (if these tests fail, it means there are some not deleted encumbrances)

MODORDERS-243 Create encumbrance upon order transition to "Open"

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-52](https://issues.folio.org/browse/MODINVOICE-52) Calculate Invoice Totals
- Verifying `adjustmentsTotal`, `subTotal` and `total` of invoice on POST and GET
- Positive Tests: `Invoice calculated totals` contains requests to verify calculated totals for invoice without, with 1 and 2 lines and lockTotal true and false
- Negative Tests: tests to validate total and lockTotal combinations
- `Create invoice with locked total but without total`
- `Update invoice with locked total changing total` - the invoice is `Approved`
- `Update invoice with locked total to false and delete total` - the invoice is `Approved`
Collection run against folio-testing back-end

MODINVOICE-52 Calculate Invoice Totals

---

mod-invoice/mod-invoice.postman_collection.json

- Adding requests to create testing ledger and fund (required for fund distributions)
- Moving tests related to workflow transition to separate directory (Workflows)
- Adding positive and negative tests to verify voucher status on invoice transition to Paid
- Separate test requests which can be made by user with invoicing permissions only and admin by different token variables
- Reducing number of tests for schemas (only one now checks if schemas loaded or any failed instead of per each schema)
Requests structure:
Positive tests:
Negative test:

MODINVOICE-36 Mark voucher as paid on transition to invoice status "Paid"

---

mod-orders/acquisitions-units.postman_collection.json

[MODORDERS-250](https://issues.folio.org/browse/MODORDERS-250) - Implement basic CRUD for /acquisitions-units/memberships
API tests form CRUD memberships.
Verified on localhost:

MODORDERS-250 - Implement basic CRUD for /acquisitions-units/memberships

---

mod-invoice/mod-invoice.postman_collection.json

- loading mock for invoices and invoiceLines once, keeping them in global variables and reusing if needed
- adding negative case to verify that it is not allowed to add invoice line for approved invoice
collection run locally:

MODINVOICE-66 Shouldn't be allowed to add invoiceLines to an "approved" or "paid" invoice

---

mod-invoice/mod-invoice.postman_collection.json

https://issues.folio.org/browse/MODINVOICE-75
https://issues.folio.org/browse/MODINVOICE-76
* added tests for the case of transition invoces to `Approved` with FundDistributions empty or percentage summary !=100
* added tests to exercise cases when Open invoice contains fields `approvedBy` and `approvalDate`
* removed FundDistribution from invoice line with minimal content

MODINVOICE-75/76 Empty Fund Distribution. Invoice approval details set by system

---

mod-orders/mod-orders.postman_collection.json

- fixing acquisitions unit assignments tests that they didn't rely on sample data
- adding negative case for transition to open when specified `contributorNameTypeId` is missed in inventory-storage
Local collection run:

MODORDERS-247 Make contributor-name-type configurable

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-173](https://issues.folio.org/browse/MODORDERS-173) ensure receiptStatus consistency between piece and poLine
1. An order exists with a poLine receiptStatus as `Pending`
2. Create 2 pieces associated with poLine with Receiving Status:
a) `Received`
b) `Expected`
2. Update one piece from `Received` -> `Expected` which should trigger an event to update poLine receiptStatus
3. Get all pieces by poLineId
4. Verify that poLine receiptStatus is updated to `Awaiting Receipt`
5. Cleanup
Verified locally in folio/testing:

MODORDER-173 - API test to ensure receiptStatus consistency between piece and poLine

---

edge-rtac/edge-rtac.postman_collection.json

It appears there is no longer a "text" instance type, so the query to `instance-types` needed to change from "text" to "Books". With this change, the tests now pass.

Changed the instance-types query to use "Books"

---

mod-invoice/mod-invoice.postman_collection.json

- setting API to invoice.source instead of UUID
Verified loacally:

MODINVOICE-77 Invoice and invoiceLine schema updates

---

mod-rtac/mod-rtac.postman_collection.json

Uploaded a newer version of mod-rtac API tests that have the setup/tear down steps to create test data on the fly.
Note that this version was created in the old gse.hosting.operations repo, and the build was running it, but for some reasons it failed to be migrated over to this repo when this repo was created.

Newer mod-rtac API tests

---

mod-users/mod-users.postman_collection.json

Several minor adjustments to account for changes to mod-users behavior:
* Can no longer use preceding wildcard in CQL queries... 
* Changed `*test*` -> `fse*` in a few places
* DELETE of a non-existent record results in a 404, not 204
* GET of a non-existent user results in 404 - Not Found
* UUID format enforced - results in a separate error 
* Changed `GET /user/foo` to `GET /user/<UUID>`
* Changed `DELETE /user/foo` to `DELETE /user/<UUID>`

fixing mod-users tests

---

mod-orders/README.md
mod-orders/mod-orders-acq-units.postman_collection.json

MODORDERS-256 Restrict search for PO, POL, Piece records based upon acquisitions unit
- Adding new collection `mod-orders-acq-units` which works with test tenant (originally introduced in https://github.com/folio-org/folio-api-tests/pull/258):
1. Log-in by existing admin user
1. Create test tenant
1. Install required modules
1. Create admin user for test tenant
1. Enable authtoken mechanism
1. Create acq units
1. Create regular user
1. Run positive tests
1. Delete test tenant
- added positive and negative for restriction creation of PO, POL, Piece records
- split the tests into folders by operation
**Note**: once the collection is completed, the second run might fail because when the DB schema is deleted for test tenant, some modules still keep open DB connection in pool. When test tenant …

MODORDERS-251 Restrict creation of PO, POL, Piece records based upon acquisitions unit

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-283
Added tests for:
- validation of ISBN
- converting ISBN 10 to ISBN 13

MODORDERS-283- validate and normalize ISBN 

---

mod-orders/mod-orders-acq-units.postman_collection.json

[MODORDERS-256](https://issues.folio.org/browse/MODORDERS-256) Restrict view of PO and POLrecords based upon acquisitions unit
Adding tests to verify restriction of getting order and order line by id operations.

MODORDERS-256 Restrict view of PO and POL records based upon acquisitions unit

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-87](https://issues.folio.org/browse/MODINVOICE-87) Calculate and persist invoice totals
[MODINVOICE-86](https://issues.folio.org/browse/MODINVOICE-86) Calculate and persist invoice line totals on creation
Main updates: `Positive Tests` -> `Invoice calculated totals`. Additional tests are added to verify:
- invoice totals are updated when invoice line is added/deleted or invoice line totals are updated.
- invoice and invoice line totals are persisted (requests to get collection of invoices/invoice lines)

MODINVOICE-86/87 Calculate and persist invoice and invoice line totals

---

mod-orders/mod-orders-acq-units.postman_collection.json

[MODORDERS-254](https://issues.folio.org/browse/MODORDERS-254) Restrict updates of PO, POL, Piece records based upon acquisitions unit
[MODORDERS-255](https://issues.folio.org/browse/MODORDERS-255) Restrict deletion of PO, POL, Piece records based upon acquisitions unit
Adding tests to verify restriction of updates/deletion order, order line and pieces by id operations.
Verified locally

MODORDERS-254/MODORDERS-255 Restrict update/deletion of PO, POL, Piece records based upon acquisitions unit

---

mod-invoice/mod-invoice.postman_collection.json

https://issues.folio.org/browse/MODINVOICE-74
* Checked invoice and voucher acqUnitIds lists for equality after invoice approval.

MODINVOICE-74 Transpose invoice acquisitions-units to voucher upon voucher creation

---

mod-organizations-storage/mod-organizations-storage.postman_collection.json

[MODORGS-40](https://issues.folio.org/browse/MODORGS-40) Perform API tests in separate tenant
The `Setup` now does following:
- creates test tenant
- enables `mod-organizations-storage`, `mod-login` and `mod-permissions`
- creates admin user with all permissions defined by enabled modules
- creates a user which has only `organizations-storage.module.all` permission
The `Cleanup` now does following:
- purges and disables all modules for test tenant
- deletes test tenant

MODORGS-40 Perform API tests in separate tenant

---

mod-orders/README.md
mod-orders/acquisitions-units.postman_collection.json
mod-orders/mod-orders-acq-units.postman_collection.json

[MODORDERS-293](https://issues.folio.org/browse/MODORDERS-293) Acquisition units - soft delete
- The collection now creates test tenant to not affect existing one
- Tests are added to verify that `DELETE /acquisition-units/units/<id>` endpoint actually does not delete record but just sets `isDeleted` flag to `true`: `Positive Tests` -> `Soft delete`
Negative tests are updated to delete unit directly from storage. Proper updates will be done in [MODORDERS-294](https://issues.folio.org/browse/MODORDERS-294)

MODORDERS-293 Acquisition units - soft delete

---

mod-invoice/mod-invoice-acq-units.postman_collection.json

[MODINVOICE-70](https://issues.folio.org/browse/MODINVOICE-70)
Added various cases for restriction update of invoice and invoice line records to `Positive Tests/Test protectUpdate`
Collection run on local vagrant-box:

MODINVOICE-70 Restrict updates of invoice, invoiceLine records based upon acquisitions unit

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-298
* Temporary removed encumbrance creation test, disabled encumbrance validation.

MODORDERS-298 Temporarily disable interaction with encumbrance APIs

---

mod-invoice/mod-invoice-acq-units.postman_collection.json

**Purpose:**
https://issues.folio.org/browse/MODINVOICE-71
**Approach:**
- Update existing collection `mod-invoice-acq-units` which works with test tenant:
1. Log-in by existing admin user
2. Create test tenant
3. Install required modules
4. Create admin user for test tenant
5. Enable authtoken mechanism
6. Create acq units
7. Create regular user
8. Create limited user
9. Run positive tests
10. Run negative tests 
11. Delete test tenant
- added positive and negative for restriction deletion of invoice, invoice-line records
- split the tests into folders by operation
**Collection run on folio-testing:**
**Collection run on folio-snapshot:**

MODINVOICE-71: API test to Restrict deletion of invoice, invoiceLine records based upon acquisitions unit

---

mod-invoice/mod-invoice-acq-units.postman_collection.json

**Purpose:**
https://issues.folio.org/browse/MODINVOICE-69
**Approach:**
- Update existing collection `mod-invoice-acq-units` which works with test tenant:
1. Log-in by existing admin user
2. Create test tenant
3. Install required modules
4. Create admin user for test tenant
5. Enable authtoken mechanism
6. Create acq units
7. Create regular user
8. Create limited user
9. Run positive tests
10. Run negative tests 
11. Delete test tenant
- added positive and negative for restriction creation of invoice, invoice-line records
- split the tests into folders by operation
**Note**: once the collection is completed, the second run might fail because when the DB schema is deleted for test tenant, some modules still keep open DB connection in pool. When test tenant is created again in less then 1 …

API tests for MODINVOICE-69 - Restrict creation of invoice, invoice-line

---

mod-orders/mod-orders-acq-units.postman_collection.json

[MODORDERS-294](https://issues.folio.org/browse/MODORDERS-294) Disallow "isDeleted" acq units to be assigned to orders
- Creating 2 more units in Setup section: fully unprotected and "soft-deleted"
- Adding set of `Soft delete` positive tests:
- Creating order with one line assigning fully unprotected and fully protected units
- Check that order, line and pieces can be retrieved
- "Delete" fully unprotected unit
- Check that any operation on order, line or piece is forbidden because user is not a member of fully protected unit
- Assign a user to fully protected unit
- Check that order still has reference on "deleted" unit but now user can operate on order and related records
- Try to update order assigning another "soft-deleted" unit 
- Negative tests are unchanged -  the cases there are …

MODORDERS-294 Disallow "isDeleted" acq units to be assigned to orders

---

mod-orders/acquisitions-units.postman_collection.json
mod-orders/mod-orders-acq-units.postman_collection.json

API Tests for [MODORDERS-286](https://issues.folio.org/browse/MODORDERS-286) - Restrict receive/checkin based on acquisitions units.
Receiving/check-in flows implemented for the following cases:
- order (protected for update) <-> order-line <-> piece with user isn't a member of units - operation is restricted
- order (protected for update) <-> order-line <-> piece with user is a member of units - operation is allowed
- order (not protected for update) <-> order-line <-> piece + any user units - operation is allowed
Regular user (with xokapitoken) creates needed orders, order-lines and pieces.
1) Another user - limited user (with xokapitoken-limitedUser) tries to check-in/receive pieces that related to non-protected for updating orders -> operation allowed.
2) This limited user tries to …

MODORDERS-286 - Restrict receive/checkin based on acquisitions units

---

mod-orders/mod-orders.postman_collection.json

Adding the missing changes in master from https://github.com/folio-org/folio-api-tests/tree/MODORDERS-298/mod-orders
and 
https://issues.folio.org/browse/MODORDERS-304
- Because of the merge conflicts in  https://github.com/folio-org/folio-api-tests/pull/292, the changes were reverted to an old version of the tests, revived the branch and applied the changes here
- Also added test for https://issues.folio.org/browse/MODORDERS-304
Tests are present for both the scenarios
1) CreateInventory = Instance, Holding ReceiptStatus= Receipt Not Required
2) CreateInventory = None, ReceiptStatus= Receipt Not Required
Passes on folio-testing:

MODORDERS-298- Fix reverted tests

---

mod-finance/mod-finance.postman_collection.json

[MODFIN-61](https://issues.folio.org/browse/MODFIN-61) Define and Implement Budget API
- Creating test fiscal year record directly in storage for now as it is required to create budget
- Creating budget records using fund and fiscal year created by preceding requests
- Positive and negative tests to test CRUD basics
- Using complex query to search for budgets like 
```
query=budgetStatus==Planned and fund.fundStatus==Active and ledger.name=test and fiscalYear.periodEnd > 2019-12-12
```

MODFIN-61 Define and Implement Budget API

---

mod-orders/README.md
mod-orders/mod-orders.postman_collection.json

[MODORDERS-303](https://issues.folio.org/browse/MODORDERS-303) Perform API tests in separate tenant
- Creating test tenant to execute all the tests
- Setup "global" data which is required to create locations (like institution, campus etc.)
- Update all the requests to `orders` endpoints to be sent under regular user
- Update all the requests to other modules' endpoints to be sent under test tenant admin (all permissions)
- Removing all the utility functions which were dealing with removal of the records from other modules

MODORDERS-303 Perform API tests in separate tenant

---

mod-orders/mod-orders.postman_collection.json

API Tests for [MODORDERS-302](https://issues.folio.org/browse/MODORDERS-302) - Create order-templates API
The following tests are implemented.
**Positive:**
1. Create order template
2. Get order template by id
3. Update order template and verify that it is updated
4. Delete order template and verify that it is deleted
**Negative:**
1. Get order templates by invalid query
2. Order template not found
3. Update order template - id mismatch
4. Delete non-existed order template

MODORDERS-302 - Create order-templates API

---

mod-invoice/mod-invoice-acq-units.postman_collection.json

[MODINVOICE-89](https://issues.folio.org/browse/MODINVOICE-89) Disallow "isDeleted" acq units to be assigned to invoice
- Creating 2 more units in the Setup section: fully unprotected and "soft-deleted"
- Adding a set of `Soft delete` positive tests:
- Creating an invoice and assigning fully unprotected and fully protected units
- Check that invoice can be retrieved
- "Delete" fully unprotected unit
- Check that any operation on the invoice is forbidden because the user is not a member of a fully unprotected unit
- Assign a user to fully protected unit
- Try to update invoice assigning another "soft-deleted" unit 
- Negative tests added to create an invoice with soft-deleted unit
**folio-snapshot**
**folio-testing**

API tests for MODINVOICE-89

---

mod-gobi/mod-gobi.postman_collection.json

[MODGOBI-83](https://issues.folio.org/browse/MODGOBI-83) Perform API tests in separate tenant
- Creating test tenant to execute all the tests
- Creating super user (all permissions), gobi user (only `gobi.all`) and user without any permissions
- Setup finance, orgs, inventory data which is required to create orders
- Update all the requests to `/gobi/xyz` endpoints to be sent under regular user
- Update all the requests to other modules' endpoints to be sent under super user (all permissions)

MODGOBI-83 Perform API tests in separate tenant

---

mod-invoice/mod-invoice.postman_collection.json

**Purpose:**
API test for https://issues.folio.org/browse/MODINVOICE-95
**Approach:**
- Add negative test to verify "Paid" invoice is not allowed to transition to "Approved", "Open", "Reviewed", "Cancelled".
- Unset/CleanUp variable
**Verified on folio-testing:**

API tests for MODINVOICE-95: Once an invoice is Paid it should no longer transition to other statuses

---

mod-invoice/mod-invoice.postman_collection.json

**Purpose:**
https://issues.folio.org/browse/MODINVOICE-103
**Approach:**
- Create invoice with adjustments but without lines
- Verify `adjustmentsTotal` equals the sum of all adjustments
Verified in folio-testing:

API tests for MODINVOICE-103

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-316](https://issues.folio.org/browse/MODORDERS-316) Prevent duplicate ISBNs
- updating test to verify that duplicate ISBNs are stripped out
- fixing order approval negative test
Merge https://github.com/folio-org/folio-api-tests/pull/315 along with this PR

MODORDERS-316 Prevent duplicate ISBNs

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-318
The recent changes to finance module schemas(FiscalYearOneId was added as a required field in ledger schema) are failing the API tests. This PR covers those changes
verified on folio-testing:

MODORDERS-318: Update according to latest finance schemas

---

mod-gobi/mod-gobi.postman_collection.json

https://issues.folio.org/browse/MODGOBI-88- Though this story deals with changing to use the supertenant to create a test tenant, there are no changes necessary for that in the API tests. Changing the environment file to use supertenant and the creds will suffice. 
The recent changes to finance module schemas(FiscalYearOneId was added as a required field in ledger schema) are failing the API tests. This PR covers those changes
verified on folio testing:
Also, using the super tenant to login initially

MODGOBI-88- Update to latest schema changes in finance

---

mod-invoice/mod-invoice.postman_collection.json

**Purpose:**
https://issues.folio.org/browse/MODINVOICE-107
**Approach:**
No changes are required in scope of this story but there are few schema changes. So update `Setup`->`Prepare finance data`->`Ledger` with `fiscalYearOneId`
**Verified in folio-testing:**
Login using supertenant tenant and its own credentials

mod-invoice - Fix schema changes from finance

---

mod-finance/mod-finance.postman_collection.json

[MODFIN-77(https://issues.folio.org/browse/MODFIN-77) Fund API updates: POST
- use CompositeFund schema instead of Fund for POST, PUT, GET by id
- added test to verify that Fund assigned to specified groups for current or next fiscalYear
- added negative case when "current" fiscalYear not found

MODFIN-77 Fund API updates: POST

---

mod-finance/mod-finance.postman_collection.json

[MODFIN-78(https://issues.folio.org/browse/MODFIN-78)
- added tests to verify GET /finance/funds/{id} assigned to current or next fiscal year

MODFIN-78 Fund API updates: GET by id/GET by query

---

mod-finance/mod-finance.postman_collection.json

**Purpose:**
https://issues.folio.org/browse/MODFIN-70
**Approach:**
- Verify the creation of allocation, transfer, encumbrance
- Retrieve transaction by id and collection of transaction
- Cleanup all created transactions
- Negative tests to handle invalid creation of transactions(allocation, transfer, encumbrance, and retrieval)
**Verified in the snapshot and folio-testing environment:**

API tests for MODFIN-70: Create transaction APIs - Allocations, Transfers, Encumbrances

---

mod-finance/mod-finance.postman_collection.json

- API tests for Group Fiscal Year Summary
- Refactoring of Group Fund Fiscal Year tests
Positive test:
1) Retrieve summary
Negative test:
1) Retrieve summary for non-existed fiscal year
Verified on localhost:

MODFIN-73 - Implement the GET /finance/group-fiscal-year-summaries API

---

mod-orders/mod-orders-acq-units.postman_collection.json
mod-orders/mod-orders.postman_collection.json

[MODORDERS-350](https://issues.folio.org/browse/MODORDERS-350)
- adding receiptDate for POST Pieces  for mod-orders and mod-orders.acq-units collections
- adding negative case when for piece creation when receiptDate is missing

MODORDERS-350 Update piece schema (receipt date)

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-117](https://issues.folio.org/browse/MODINVOICE-117)
- adding tests to verify transition to approve without or with invalid adjustment.fundDistributions
- adding verification that adjustment's fundDistribution is taken to account upon transition to approve

MODINVOICE-117 Include invoice level Fund distributions in Voucher information summary

---

mod-orders/mod-orders-acq-units.postman_collection.json
mod-orders/mod-orders.postman_collection.json

[MODORDERS-349](https://issues.folio.org/browse/MODORDERS-349)
- updated test according to poLine schema changes
- fixed the ledger, budget records to be able create an encumbrance upon opening an order
- fixed test after breaking changes in inventory-storage related to item status
folio-testing:

MODORDERS-349 Make title schema changes to all APIs

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

add tests to cover https://issues.folio.org/browse/MODKBEKBJ-353
* add tests for following endpoint:
PUT /eholdings/packages/{id}
* add tear-down requests to unassign access types from packages

MODKBEKBJ-353 Add API tests

---

mod-orders/mod-orders.postman_collection.json

API Tests for [MODORDERS-328](https://issues.folio.org/browse/MODORDERS-328).
Positive tests:
CRUD operations for reason for closure, prefix, suffix:
1. Create
2. Get by id
3. Update/Get by Id
4. Get collection
5. Delete/Get by Id
Negative tests:
1. Get by invalid query
2. Get - not found
3. Update - id mismatch
4. Delete - not found

MODORDERS-328 - Migrate orders settings from mod-configuration

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

add tests to cover:
* https://issues.folio.org/browse/MODKBEKBJ-355
* https://issues.folio.org/browse/MODKBEKBJ-356
* https://issues.folio.org/browse/MODKBEKBJ-375
* https://issues.folio.org/browse/MODKBEKBJ-376
Add tests for following endpoint:
* GET/eholdings/packages
* GET/eholdings/packages/{id}/resources
* GET/eholdings/provider/{id}/packages
* GET/eholdings/titles

MODKBEKBJ Add API tests for access type filtering

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-371](https://issues.folio.org/browse/MODORDERS-371)
added test to verify that there are no extra pieces upon opening order with PoLine (P/E Mix): physicalQty: 2, electronicQty: 2, createInventory (Phys): Instance, Holding, Item, createInventory (Elec): None
folio-snapshot

MODORDERS-371 Extra pieces are created for "PO Line" with type for "P/E Mix"

---

mod-finance/mod-finance.postman_collection.json

https://issues.folio.org/browse/MODFIN-117
need to update API test with case to test meaningful error message upon failed budget deletion
Verified on testing env.

[MODFIN-117] Add API test for error message

---

mod-finance/mod-finance.postman_collection.json

[MODFISTO-96](https://issues.folio.org/browse/MODFISTO-96)
- adding test for de-referencing with group_fund_fiscal_year records upon budget deletion
local vagrant box

MODFISTO-96 Add logic upon budget deletion

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

add tests to cover:
* https://issues.folio.org/browse/MODKBEKBJ-419
* https://issues.folio.org/browse/MODKBEKBJ-420
* https://issues.folio.org/browse/MODKBEKBJ-421
* https://issues.folio.org/browse/MODKBEKBJ-422
* https://issues.folio.org/browse/MODKBEKBJ-423
Add tests for following endpoint:
* GET /eholdings/kb-credentials
* POST /eholdings/kb-credentials
* GET /eholdings/kb-credentials/{id}
* PUT /eholdings/kb-credentials/{id}
* DELETE /eholdings/kb-credentials/{id}

MODKBEKBJ-423 Add API tests for managing kb-credentials

---

mod-data-export/mod-data-export.postman_collection.json

https://issues.folio.org/browse/MDEXP-78
- Add test for checking if /data-export/fileDefinitions/{{fileDefinitionId}}/upload is idempotent
- Modified login test to take parameters from environment file rather than from our utils
- as we should not be storing username passoword
- These hard coded values will not work on other environments
- Reference environments changed the way we can create tenants

MDEXP-78: adding tests for /upload end point idempotent

---

mod-finance/mod-finance.postman_collection.json
mod-invoice/mod-invoice.postman_collection.json

[MODFISTO-85](https://issues.folio.org/browse/MODFISTO-85) - Update the transaction 'source' enum
* fixed API tests for `mod-finance` and `mod-invoice`, `mod-orders` works properly.
* mod-finance
* mod-orders
* mod-invoice

MODFISTO-85 - Update the transaction 'source' enum

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-389](https://issues.folio.org/browse/MODORDERS-389)
- adding test requests to check deletion of prefix/suffix not allowed if they used by any order
folio-testing

MODORDERS-389 Unable to remove prefixes/suffixes that are currently used by an existing orders

---

mod-data-export/mod-data-export.postman_collection.json

CRUD API tests for job profile APIs
- Moved mapping profiles and job profiles to their own folder
- Cleaning up them in the end as we need to use them in export jobs eventually

MDEXP- 145- Job Profile APIs CRUD

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-168](https://issues.folio.org/browse/MODINVOICE-168)
Fixed invoiceLine creation for workflow tests to not use same fundId
Added verification that voucherLines have fund code after approval
Verified on folio-snapshot

MODINVOICE-168 Populate field "voucherLine.fundDistribution.code" upon Invoice approval

---

mod-finance/mod-finance.postman_collection.json

[MODFISTO-114](https://issues.folio.org/browse/MODFISTO-114)
Fixed "Get ledger record with summary after 2nd encumbrances update" test

MODFISTO-114 Ledger FY totals not updated after encumbrance update
