mod-circulation-storage/mod-circulation-storage.postman_collection.json

@magdazacharska Please Review
@mreno-EBSCO FYI...

CIRCSTORE-58-testcases for limit/offset

---

mod-kb-ebsco/mod-kb-ebsco.postman_collection.json

Some of our tests started failing with following bug fixes that went in over the last week in mod-kb:
https://issues.folio.org/browse/UIEH-485
https://issues.folio.org/browse/UIEH-489
Update tests accordingly and add where necessary.

Update mod-kb-ebsco tests

---

mod-inventory-storage/mod-inventory-storage-contributor-name-types.postman_collection.json
mod-inventory-storage/mod-inventory-storage-contributor-types.postman_collection.json
mod-inventory-storage/mod-inventory-storage.postman_collection.json

update meant to fix schema validation in mod-inventory-storage

update for schema version

---

mod-gobi/mod-gobi.postman_collection.json

* Add /gobi/orders tests (positive and negative)
* Setup/Cleanup a user w/o permissions for use in negative tests
* Update the /validate negative test (user w/o permissions) to be env independent

adding /gobi/orders test cases

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Adjusted tests for
- get package by id and
- get package collection endpoints
-"providers / GET Provider by providerId / with valid providerId including packages"
-"providers / PUT provider by providerId"
changes made to tests:
1)Deleted check for "vendorId", "vendorName" - those attributes shouldn't
be returned
2)Adjusted test error messages to format "Invalid Query Parameter for sort"
3)Changed tests for invalid page and count parameters to expect plain text
error
4) Changed "providers / PUT provider by providerId / update request - invalid json"
   - changed this test to not expect json response - invalid json body
   causes 400 error with plain text body to be returned, we can't change that behaviour

Modkbekbj 67 add packages tests

---

edge-oai-pmh/edge-oai-pmh.postman_collection.json

- Added API tests for the Identify verb
- Updated API Tests for LIstMetadataFormats verb
- Added API tests for GetRecord
- Added API tests for the ListRecords verb
- Added API tests for the ListIdentifiers verb
- Added API tests for ListSets

EDGOAIPMH-16-OAI-PMH-API-Tests

---

mod-orders/mod-orders.postman_collection.json

Create API tests  - https://issues.folio.org/browse/MODORDERS-58

API tests for mod-orders GET orders/id and POST /orders endpoints

---

mod-gobi/mod-gobi.postman_collection.json

This has the API tests to create a tenant specific configuration for order Mapping and verify that they were honored while a gobi order is created

Modgobi 35

---

edge-oai-pmh/edge-oai-pmh.postman_collection.json

Updating edge-oai-pmh API tests to prepare/clean up the data for SRS module

 MODOAIPMH-57 Migrate to SRS

---

edge-oai-pmh/edge-oai-pmh.postman_collection.json

- Add required permission depending on storage type

MODOAIPMH-57 Migrate to SRS

---

mod-gobi/mod-gobi.postman_collection.json

This PR contains changes to:
1) add combinator & translation specific tenant config override tests
2) delete orders after creation

Adding tenant specific configs

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-90 we want to have API tests for GET `/eholdings/status` endpoint
- added tests on valid response content
- added tests on valid data attributes
- added tests on expected fields

MODKBEKBJ-90 - API Tests GET /eholdings/status endpoint

---

mod-orders/mod-orders.postman_collection.json

1. Integrate with DELETE API-test
2. Cleanup - move all delete tests to the cleanup folder

Integrate with del api-test, cleanup

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-94 we want to have API Tests for GET /eholdings/root-proxy endpoint
-  added api tests for GET `/eholdings/root-proxy endpoint` to the mod-kb-ebsco-java postman collection

MODKBEKBJ-94 - API Tests GET /eholdings/root-proxy endpoint

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Add tests for post resources
1) Removed checks for attributes edition, description, coverageStatement,
publisherName, vendorId, vendorName
2) Changed expected error message in test "/resources POST invalid content type"

MODKBEKBJ-76: post resource tests

---

mod-orders/mod-orders.postman_collection.json

URI path parameters pattern validation

MODORDERS-95 Path param pattern validation

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Per https://issues.folio.org/browse/MODKBEKBJ-68 we want to have API Tests GET /eholdings/packages/{packageId}?include=resources endpoint

MODKBEKBJ-68 - API Tests GET /eholdings/packages/{packageId}?include=resources endpoint

---

mod-orders/mod-orders.postman_collection.json

API test updates is needed according to redefined and new implemented endpoints due the story https://issues.folio.org/browse/MODORDERS-124
Updating API tests

MODORDERS-127 redefined collection of API tests according to updated endpoints

---

mod-orders/mod-orders.postman_collection.json

API tests changes in addition to PR https://github.com/folio-org/folio-api-tests/pull/69/ according to [MODORDERS-107](https://issues.folio.org/browse/MODORDERS-107).

MODORDERS-107 - API Tests for GET /po_number (PR#2)

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-142
* added tests for GET /orders/orders/order-lines
* fixed tests after po_line naming updates due PR https://github.com/folio-org/mod-orders/pull/91

MODORDERS-142 tests for GET /orders/orders/order-lines

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Updated tests for https://issues.folio.org/browse/MODKBEKBJ-170
Updated tests for tags and added new tag schema.

MODKBEKBJ-170 API Tests: Providers Endpoint Updates for Tags

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Updates for resource tags according to https://issues.folio.org/browse/MODKBEKBJ-172.
* updated tests for resources
* moved tests for title attributes into a separate folder
Tests were run against `testing` vagrant box using Postman Collection Runner
- newman console collection runner posts errors related to `Unexpected token u in JSON at position 0                                                                                             
at test-script` periodically and probably should be investigated in future.

MODKBEKBJ-172 - API Tests: Resources Endpoint Update for Tags

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

Updated tests for https://issues.folio.org/browse/MODKBEKBJ-171
Updated tests for packages

MODKBEKBJ-171 API Tests: Packages Endpoint Updates for Tags

---

edge-oai-pmh/edge-oai-pmh.postman_collection.json

Updating SRS endpoint names and content properties

MODOAIPMH-66 Upgrade to source-record-storage 2.0 interface

---

mod-kb-ebsco/mod-kb-ebsco-java.postman_collection.json

updated titles tests for tags for https://issues.folio.org/browse/MODKBEKBJ-173
Updated and added new tests for titles

MODKBEKBJ-173 API Tests: Titles Endpoint update for Tags

---

mod-codex-mux/mod-codex-mux.postman_collection.json

Creating api test for mod-codex-mux.
https://issues.folio.org/browse/MODCXMUX-39
Creating setUp for tests
Taking schemes needed for testing

MODCXMUX-39 API Tests: Create mod-codex-mux API Test Collection

---

edge-rtac/edge-rtac.postman_collection.json
environment/folio-vagrant.postman_environment

Fixing the edge-rtac tests which were very brittle.  Prior to this any failure would result in lingering test data. 
[EDGRTAC-7](https://issues.folio.org/browse/EDGRTAC-7)
* use the existing record if a test record already exists, create it otherwise
* introduction of a global utilities for repeated actions (record retrieval, etc.)
* switch variable names to be in-line with the community environment file (edge.host, edge.apikey, etc.)
* switch instance-type from "Book" (no longer used) to "text"

EDGRTAC-7: fixing edge-rtac tests

---

mod-codex-ekb/mod-codex-ekb.postman_collection.json

Adding coverage for new endpoints. 
https://issues.folio.org/browse/MODCXEKB-86
Adding tests for getPackageById endpoint.

MODCXEKB-86 API Tests: Get Package By Id

---

mod-codex-mux/mod-codex-mux.postman_collection.json

Test  /codex-packages-sources endpoint
Implemented test, 
Fixed configuration tear-down

MODCXMUX-42 Add test for /codex-packages-sources

---

mod-codex-ekb/mod-codex-ekb.postman_collection.json

Covering by tests for codex-packages endpoint.
https://issues.folio.org/browse/MODCXEKB-87
Adding tests for getPackagesCollection endpoint

MODCXEKB-87 API Tests: Get Packages Collection

---

mod-codex-ekb/mod-codex-ekb.postman_collection.json
mod-codex-mux/mod-codex-mux.postman_collection.json

Covering get instance by id endpoint by tests.
https://issues.folio.org/browse/MODCXMUX-43
Creating tests for get instance by id endpoint

MODCXMUX-43 API Tests: Get Instance by Id

---

mod-codex-ekb/mod-codex-ekb.postman_collection.json
mod-codex-mux/mod-codex-mux.postman_collection.json

Covering get instances collection endpoint by tests.
https://issues.folio.org/browse/MODCXMUX-44
Creating api tests for get instances collection endpoint.

MODCXMUX-44 API Tests: Get Instances Collection

---

mod-orders/mod-orders.postman_collection.json

API tests for POST /orders/peices endpoint implemented in JIRA: [MODORDERS-185](https://issues.folio.org/browse/MODORDERS-185) (PR [#117](https://github.com/folio-org/mod-orders/pull/117)).

MODORDERS-185 - Checkin: Implement POST /orders/peices endpoint

---

mod-codex-ekb/mod-codex-ekb.postman_collection.json
mod-codex-mux/mod-codex-mux.postman_collection.json

Covering get package by id endpoint by tests
https://issues.folio.org/browse/MODCXMUX-40
Adding tests for get package by id endpoint

MODCXMUX-40 API Tests: GET Package by Id

---

mod-users-bl/mod-users-bl.postman_collection.json

mod-users-bl build fails in FSE due to schema changes. 
Two status code changes from 400 -> 422 for incorrect username/password, am unsure if these changes are intended. Creating this PR to fix the build in our pipeline.

Update mod-users-bl tests

---

edge-oai-pmh/edge-oai-pmh.postman_collection.json

[EDGOAIPMH-29](https://issues.folio.org/browse/EDGOAIPMH-29) Update API Tests
Updating test requests to create SRS records according to latest changes
- `POST /source-storage/snapshots`: status is changed to `PARSING_IN_PROGRESS`
- `POST /source-storage/records`: `matchedId` is required and random uuid is used for test requests
- Create snapshot
- Create record

EDGOAIPMH-29 Update API Tests

---

mod-invoice/mod-invoice.postman_collection.json

https://issues.folio.org/browse/MODINVOICE-19
Created API test skeleton including following parts:
* Created folders for Setup, Positive tests, Negative tests, Cleanup
* Setup folder contains authorization request, requests for verifying modules deployed, requests for getting validation schemas.

MODINVOICE-19 Create API test skeleton

---

mod-organizations-storage/mod-organizations-storage.postman_collection.json

- Prepare basic utility functions
- Create an user with `organizations-storage.module.all` permission only and use this user for all requests to organizations storage
- Load all schemas required for validation
- Create a few organization to verify that validation against schema approach works fine
- Delete created organizations
- Delete created user
Initial structure
Collection run on local vagrant box
TODO

MODORGS-5 Create API Test Skeleton

---

mod-notes/mod-notes.postman_collection.json

https://issues.folio.org/browse/MODNOTES-79
Creating API tests for note-types endpoint
Sorting tests by folders
Creating setup data for tests

MODNOTES-79 API Tests for GET /note-types

---

mod-notes/mod-notes.postman_collection.json

https://issues.folio.org/browse/MODNOTES-83
Creating API tests for note-type endpoint.

MODNOTES-83 API Tests for DELETE /note-types/{typeId}

---

mod-notes/mod-notes.postman_collection.json

Covering get /notes by api tests
https://issues.folio.org/browse/MODNOTES-74
Adding tests for get /notes endpoint.

MODNOTES-74 API Tests for GET /notes

---

mod-notes/mod-notes.postman_collection.json

Covering GET/notes by api tests
https://issues.folio.org/browse/MODNOTES-76
Adding tests for GET/notes/{id} endpoint.

MODNOTES-76 API Tests for GET /notes/{id}

---

mod-notes/mod-notes.postman_collection.json

Covering /notes endpoint by tests.
https://issues.folio.org/browse/MODNOTES-75
Creating API tests for post notes endpoint.

MODNOTES-75 API Tests for POST /notes

---

mod-notes/mod-notes.postman_collection.json

Covering /notes endpoint by tests.
https://issues.folio.org/browse/MODNOTES-77
Creating API tests for put notes endpoint.

MODNOTES-77 API Tests for PUT /notes/{id}

---

mod-notes/mod-notes.postman_collection.json

Covering DELETE /notes/{id} endpoint by tests.
https://issues.folio.org/browse/MODNOTES-78
Adjust existing tests to recent changes

MODNOTES-78 API Tests for DELETE /notes/{id}

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-225](https://issues.folio.org/browse/MODORDERS-225): To switch to use mod-organizations-storage instead of mod-vendors

MODORDERS-225: Switch to use mod-organizations-storage

---

mod-invoice/mod-invoice.postman_collection.json

- added create invoice with min content
- updated create invoice to check that folioInvoiceNo is generated by system
- added create invoice with missing required fields
- added utils.validateInvoiceWithMinimalContent function
- added utils.buildInvoiceWithMinContent function
Collection run on local env:

MODINVOICE-20 Implement POST /invoicing/invoices

---

mod-invoice/mod-invoice.postman_collection.json

**Purpose:**
API tests for the following user stories:
https://issues.folio.org/browse/MODINVOICE-43
https://issues.folio.org/browse/MODINVOICE-28
Tested in `folio-testing-okapi.aws.indexdata.com`
Collection Runner:

MODINVOICE-43: API Tests for GET /invoice/invoices

---

mod-notes/mod-notes.postman_collection.json

Fixing test fails.
https://issues.folio.org/browse/MODNOTES-98
Fixing tests on post and put note-types endpoints

MODNOTES-98 Failing API tests

---

mod-invoice/mod-invoice.postman_collection.json

added positive and negative test cases
Collection run on local env

MODINVOICE-31 Implement PUT /invoicing/invoices/{id}

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Adding tests for package filtering by tags.
https://issues.folio.org/browse/MODKBEKBJ-225
Adding new tests for particular endpoint.

MODKBEKBJ-225 API Tests - Filtering by tags only - Package Level

---

mod-orders/mod-orders.postman_collection.json

Searching and filtering by Order parameter, sorting by PoLine parameter both for asc and desc.
* Positive test, ascending sorting (`Get Order Lines` folder): 
* Positive test, descending sorting:
* Negative test (`Lines` folder):
Passed tests against testing environment

MODORDERS-220 API Tests to cover order-line search and filtering

---

mod-invoice/mod-invoice.postman_collection.json

**Purpose:**
https://issues.folio.org/browse/MODINVOICE-39
https://issues.folio.org/browse/MODINVOICE-40
**Approach:**
- Verify positive and negative tests for GET and PUT voucher-line by id
- CleanUp
**Verification:**

API tests for MODINVOICE-39 and MODINVOICE-40

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Add tests for GET /providers with filter[tags] parameter

MODKBEKBJ-224 Add tests for GET /providers with filter[tags] parameter

---

mod-orders/mod-orders.postman_collection.json

Negative scenario in addition to PR [#171](https://github.com/folio-org/folio-api-tests/pull/171).

MODORDERS-219 - Update API Tests to cover order search and filtering

---

mod-invoice/mod-invoice.postman_collection.json

Aligning functions with schema changes:
- Updating tests to work with updated records content
- Updating `utils.buildInvoiceLineWithMinContent` and `utils.buildInvoiceWithMinContent` to build record with minimal required properties
- Updating `utils.validateInvoiceWithMinimalContent` and `utils.validateInvoiceLineWithMinimalContent` to validate created records
Collection run on testing env:

MODINVOICE-42/49 schema updates

---

mod-invoice/mod-invoice.postman_collection.json

- fixing ids reference between records
- clean-up order
Collection run on folio-testing:

MODINVOSTO-18 Add foreign key constraints on voucherLine.voucherId

---

mod-invoice/mod-invoice.postman_collection.json
mod-orders/mod-orders.postman_collection.json

[MODINVOICE-47](https://issues.folio.org/browse/MODINVOICE-47) Implement GET /voucher/voucher-number/start
Adding one positive and negative requests
Note: the changes from https://github.com/folio-org/folio-api-tests/pull/206 were cherry-picked to make this PR fully working

MODINVOICE-47 Verify GET /voucher/voucher-number/start

---

mod-invoice/mod-invoice.postman_collection.json

API Tests for [MODINVOICE-35](https://issues.folio.org/browse/MODINVOICE-35)

MODINVOICE-35 - Prevent modifications to invoice/invoice lines once status is "Approved"

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Adding api tests for the functionality implemented to display assigned package tags in a list of packages associated with a provider.
https://issues.folio.org/browse/MODKBEKBJ-244
Adding new tests for particular endpoint.
Also I have deleted some extra tests request and transfer requests to right folder.

MODKBEKBJ-244 API Tests : Provider | List of Packages | Display assigned package tags

---

mod-invoice/mod-invoice.postman_collection.json

https://issues.folio.org/browse/MODINVOSTO-19
* Added tests to exercise this case
* In addition, fixed issue about 404 error on the getting mock file request.

MODINVOSTO-19 Remove associated invoice-lines when removing an invoice

---

mod-invoice/mod-invoice.postman_collection.json

**Purpose:**
https://issues.folio.org/browse/MODINVOICE-57
**Approach:**
- One positive test
- Negative test already exists
**Verified in folio-testing:**

MODINVOICE-57 : API tests to GET of list of vouchers

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Add api test for getting resource tags  for endpoint "titles/{id}?include=resources"

MODKBEKBJ-246 Add api test for getting resource tags for title

---

mod-orders/mod-orders.postman_collection.json

New requests : 
1) Create empty order : 
2) Get list of orders by empty query : 
3) Delete empty order :
4) Verified tests on local environment :

MODORDSTOR-86 orders without po lines are not returned

---

mod-gobi/mod-gobi.postman_collection.json

https://issues.folio.org/browse/MODGOBI-72
1. Added test to ensure that duplicate Orders are not created with same YBPOrderNumber
Additional Changes
1. Refactored tests to user user with permissions limited to only **gobi**. Repurposed the existing user creation requests
New tests structure
Verified against **folio-snapshot**

MODGOBI-72-Prevent duplicate Orders

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Add/adjust api tests to filter by tags only when searched within list of titles.
Adding new test requests for particular endpoint.

MODKBEKBJ-248 API Tests - Update packages (search within titles ) to filter by tags only

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Adjust/add api tests such that a list of titles associated with a package returns its associated tags in the response. Implementation story - MODKBEKBJ-241
Adding tests for particular endpoint.

MODKBEKBJ-247 API Tests: Package | List of Titles | Display assigned resource tags

---

mod-orders/mod-orders.postman_collection.json

Adding a few tests to verify default values of PO and POL

MODORDSTOR-98 filterable boolean properties to have default value

---

mod-orders/acquisitions-units.postman_collection.json

New collection created to verify `acquisitions-units` APIs

MODORDERS-249 Implement basic CRUD for /acquisitions-units/units

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Making tests more realistic
Changing tests bodies in PUT request

MODKBEKBJ-253 Provider: Make api tests payloads more realistic

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Make title request more realistic
Add id field to title requests because UI sends this field in PUT requests

MODKBEKBJ-265 make title requests realistic

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Make resource requests more realistic
Add fields related to title

MODKBEKBJ-270: Update resource requests to match real requests

---

mod-organizations-storage/mod-organizations-storage.postman_collection.json

While running these API tests against a different environment they were failing because of some environment specific checks for count returned . Also found a query which needs correction

correcting query and checks

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Making api tests more realistic.
Adding new fields to PUT request bodies.
Adding new teardown request for cleaning db from test resources.

MODKBEKBJ-268 Package: Make api tests payloads more realistic

---

mod-organizations-storage/mod-organizations-storage.postman_collection.json

https://issues.folio.org/browse/MODORGS-31
* Implemented API CRUD tests for interface credentilas endpoint

MODORGS-31 created interface credentials tests

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Add test for "/packages/{id}/tags" endpoint

MODKBEKBJ-280 tests for updating package tags

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-247](https://issues.folio.org/browse/MODORDERS-247) Contributor name type is required field
- Creating contributor name type for tests in `Setup` section and deleting in `Cleanup`
- Using created contributor name type for all test PO lines

MODORDERS-247 Contributor name type is required field

---

mod-orders/mod-orders.postman_collection.json

New tests:
Verified on local env:

MODORDERS-266 CRUD tests for acquisition unit assignments

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Add API tests for PUT /providers/{id}/tags.
Updating api test collection by adding new request for PUT /providers/{id}/tags.

MODKBEKBJ-281 Add separate endpoint for updating provider tags

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Add API tests for PUT /resources/{id}/tags
Updating api test collection by adding new request for PUT /resources/{id}/tags.

MODKBEKBJ-282 Add separate endpoint for updating resource tags

---

mod-orders/acquisitions-units.postman_collection.json

https://issues.folio.org/browse/MODORDSTOR-100 - Acquisitions unit names should be unique

MODORDSTOR-100- Adding  tests for duplicate units

---

mod-notes/mod-notes.postman_collection.json

API test in scope of https://issues.folio.org/browse/MODKBEKBJ-290 
* added tests to search note by note type

MODKBEKBJ-290 - Ability to filter by notes types

---

mod-users-bl/mod-users-bl.postman_collection.json

2 new schemas were missing in the API test validations: Added the new schemas to the tests:
1. servicepointsexpandeduser.json
2.servicepoint.json

mod-users-bl API test fixes

---

mod-notify/mod-notify.postman_collection.json

Update error message to include tenant information from *No suitable module found for path /notify/_username* to *No suitable module found for path /notify/_username for tenant fs00000000* when we try to notify a user whose username is not present

mod-notify: update error message

---

mod-invoice/mod-invoice.postman_collection.json

https://issues.folio.org/browse/MODINVOICE-81
* added Documents tests

MODINVOICE-81 added documents test

---

mod-invoice/mod-invoice.postman_collection.json

https://issues.folio.org/browse/MODINVOICE-90
* added GET voucher-lines tests
Verified on folio testing :

MODINVOICE-90 added GET voucher-lines test

---

mod-invoice/mod-invoice.postman_collection.json

https://issues.folio.org/browse/MODINVOICE-91
* updated voucherNumberPrefix check

MODINVOICE-91 updated voucherNumberPrefix check

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

As a part of https://issues.folio.org/browse/MODKBEKBJ-283 we would like to adjust API tests with regards to changes done in  https://github.com/folio-org/mod-kb-ebsco-java/pull/175
* updated tests
Run Newman and Postman API tests against the local vagrant environment

MODKBEKBJ-283 - Remove update of package tags from package endpoints

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

As a part of https://issues.folio.org/browse/MODKBEKBJ-286 we would like to adjust API tests with regards to changes done in https://github.com/folio-org/mod-kb-ebsco-java/pull/176
Updated tests

MODKBEKBJ-286 Remove update of provider tags from provider endpoints

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

As a part of https://issues.folio.org/browse/MODKBEKBJ-287 we would like to adjust API tests with regards to changes done in https://github.com/folio-org/mod-kb-ebsco-java/pull/177
Update tags.

MODKBEKBJ-287 Remove update of resource tags from resource endpoints

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Add tests for new "isFullPackage" flag
Set up a package with 1 selected title and try updating it with true/false values for "isFullPackage" flag

MODKBEKBJ-311: Add API tests for updating partially selected package

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-61](https://issues.folio.org/browse/MODINVOICE-61) Prorated adjustments part 3 - fractional amounts
Updated existing "Prorated adjustments" positive tests (new in bold)
1. Create invoice with percentage adjustment prorated "By line"
1. Create first invoice line which has non prorated adjustment with fixed amount
1. Add adjustment to invoice with "amount" prorated "By line"
1. Create second invoice line without any adjustments
1. Add adjustment to invoice with "amount" prorated "By amount"
1. Add percentage adjustment to invoice prorated "By amount"
1. Create third invoice line without any adjustments
1. Add adjustment to invoice with "amount" prorated "By quantity"
1. Update first invoice line's subtotal to negative value so invoice's subtotal becomes zero
1. **Make invoice …

MODINVOICE-61 Prorated adjustments part 3 - fractional amounts

---

mod-gobi/mod-gobi.postman_collection.json

Added tests for splitting ISBN qualifier to a separate field
- Added a test with qualifier in both subfields

MODGOBI-86- ISBN qualifier tests

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-99](https://issues.folio.org/browse/MODINVOICE-99) Fund Distribution schema changes
- updating fundDistributions fields according to the schema changes
- adding test cases to verify ability approve invoice with invoice line containing mixed types of fundDistributions

MODINVOICE-99 Fund Distribution schema changes

---

mod-finance/mod-finance.postman_collection.json
mod-invoice/mod-invoice.postman_collection.json

https://issues.folio.org/browse/MODFIN-60
* Implementing CRUD tests for ledgers API
Verified against folio testing:

MODFIN-60 Ledger CRUD tests

---

mod-finance/mod-finance.postman_collection.json

https://issues.folio.org/browse/MODFIN-69
* Implementing Fiscal-years CRUD tests 
Verified against folio testing:

MODFIN-69 Fiscal-years CRUD tests implemented

---

mod-finance/mod-finance.postman_collection.json

[MODFIN-68](https://issues.folio.org/browse/MODFIN-68) Implement Groups API
- added positive and negative tests for Group API

MODFIN-68 Implement Groups API

---

mod-codex-ekb/mod-codex-ekb.postman_collection.json

Change tests after required permissions are added to mod-codex-ekb in https://github.com/folio-org/mod-codex-ekb/pull/105/files

MODCXEKB-98: Adjust tests after adding required permissions

---

mod-codex-mux/mod-codex-mux.postman_collection.json

Set up and tear down permissions for mod-codex-mux during tests
Copy permission requests from mod-kb-ebsco-java tests

MODCXMUX-55: Adjust tests after adding required permissions

---

mod-invoice/mod-invoice.postman_collection.json

- added test to verify possibility pay invoice with line w/o poLineId
- fixed ledger creation

MODINVOICE-97 Can not pay the invoice

---

mod-invoice/mod-invoice.postman_collection.json

https://issues.folio.org/browse/MODINVOICE-84
* use finance business logic module
Verified locally

MODINVOICE-84 use finance business logic module

---

mod-finance/mod-finance.postman_collection.json

**Purpose:**
https://issues.folio.org/browse/MODFIN-94
**Approach:**
- Create fiscal year without series but it calculates and creates it
- Verify series created
**Verified in folio-testing:**

API tests for Add series field while creating a FiscalYear

---

mod-finance/mod-finance.postman_collection.json

https://issues.folio.org/browse/MODFIN-65
currency to be picked from configuration while creating Fiscal years

MODFIN-65- adding currency while creating FY

---

mod-finance/mod-finance.postman_collection.json

https://issues.folio.org/browse/MODFIN-82
* implemented awaiting payment tests

MODFIN-82 implemented awaiting payment tests

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-299
* Resumed encumbrance creation test, disabled encumbrance validation.

MODORDERS-299 Re-integrate with encumbrance API

---

mod-gobi/mod-gobi.postman_collection.json

https://issues.folio.org/browse/MODFISTO-59
with encumbrance re Integration. GOBI tests expect a budget to be present while creating orders
- create budget as a pre-requisite

MODFISTO-59: Add budget

---

mod-finance/mod-finance.postman_collection.json

https://issues.folio.org/browse/MODFIN-98
- added get ledger by id with summary tests after creation of allocation, transfer, encumbrance
- added negative test when ledgerFY record not found

MODFIN-98 Ledger not displaying correct allocated total

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Adjust API tests for custom labels
Add userDefinedFields tests for following endpoints:
1) PUT resources/{id} 
2) GET resources/{id} 
3) GET packages/{id}?include=resources
4) GET packages/{id}/resources
5) GET titles/{id}?include=resources
Move setup and tear-down folders into a common folder so that they can
be run together from Postman runner

MODKBEKBJ-335: Change API tests to check for userDefinedFields

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Change API test for POST /titles to check for userDefinedFields

MODKBEKBJ-334: Change API test for POST /titles to check for userDefinedFields

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

cover functionality added for custom labels
https://issues.folio.org/browse/MODKBEKBJ-341
* updated kb-java API tests collection
* added tests to cover GET /custom-labels collection
* added tests to cover GET /custom-labels/{id}
* added tests to cover PUT /custom-labels/{id}

MODKBEKBJ-341 - Custom labels: update custom labels list

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

add tests to cover https://issues.folio.org/browse/MODKBEKBJ-343 
* added API tests for DELETE /custom-labels{id}

MODKBEKBJ-343 - Custom labels: delete custom label

---

mod-finance/mod-finance.postman_collection.json

API tests for [](https://issues.folio.org/browse/MODFIN-106)
Positive test:
Negative test:

MODFIN-106 - API Tests

---

mod-orders/mod-orders.postman_collection.json

**Purpose:**
API test for https://issues.folio.org/browse/MODORDERS-340
**Approach:**
- Update test data with call number
- During `check-in` and `receive`, verify that `itemLevelCallNumber` exists in an item in inventory
**Verify:**
folio-snapshot:

API tests for MODORDERS-340

---

mod-orders/mod-orders.postman_collection.json

**Purpose:**
https://issues.folio.org/browse/MODORDERS-315
**Approach:**
- Existing test data is valid for this story so only add test to verify if itemStatus is "In process"
Verified in folio-testing:

API test for MODORDERS-315

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-348
* added titles tests

MODORDERS-348 added titles tests

---

mod-finance/mod-finance.postman_collection.json

https://issues.folio.org/browse/MODFIN-83
* Implemented release encumbrance test

MODFIN-83 implemented release encumbrance test

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

add tests to cover https://issues.folio.org/browse/MODKBEKBJ-348
added tests for following endpoints: 
  ** GET /eholdings/access-types
  ** POST /eholdings/access-types
  ** GET /eholdings/access-types/{id}
  ** PUT /eholdings/access-types/{id}
  ** DELETE /eholdings/access-types/{id}

MODKBEKBJ-348 -  Settings: CRUD Access Status Types

---

mod-finance/mod-finance.postman_collection.json

**Purpose:**
API tests for https://issues.folio.org/browse/MODFIN-71
**Approach:**
- Add positive tests for payments and credits
- Add negative tests
- Cleanup
**Verified in folio-testing:**

API test for MODFIN-71

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

add tests to cover https://issues.folio.org/browse/MODKBEKBJ-349
added tests for following endpoint:
** POST /eholdings/packages

MODKBEKBJ-349 Add API tests

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

add tests to cover https://issues.folio.org/browse/MODKBEKBJ-350
added tests for following endpoint:
** PUT /eholdings/packages/{id}

MODKBEKBJ-350 Add API tests

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-113](https://issues.folio.org/browse/MODINVOICE-113)
- added requests to create encumbrances before invoice approval
- added requests to verify that encumbrances updated upon approval
folio-snapshot:

MODINVOICE-113 Call awaiting-payment API upon invoice approval

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-127](https://issues.folio.org/browse/MODINVOICE-127) Create Batch-group CRUD API
- added positive tests:
- added negative tests:
- positive tests:
- negative tests:

MODINVOICE-127 Create Batch-group CRUD API

---

mod-finance/mod-finance.postman_collection.json

* https://issues.folio.org/browse/MODFIN-86
* Added budget restriction tests
* fixed enpoints, permissions, okapi token usage
* removed invoice and invoice line creation 
Verified locally for now

MODFIN-86 implemented api tests

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

add tests to cover https://issues.folio.org/browse/MODKBEKBJ-380
* add tests for following endpoint:
DELETE /eholdings/access-types/{id}

MODKBEKBJ-380 Add API tests

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

add tests to cover https://issues.folio.org/browse/MODKBEKBJ-354
* add tests for following endpoint:
PUT /eholdings/resources/{id}

MODKBEKBJ-354 Add API tests

---

mod-invoice/mod-invoice.postman_collection.json

API tests for batch voucher export configurations.  See [MODINVOICE-128](https://issues.folio.org/browse/MODINVOICE-128)

MODINVOICE-128 - changes for batch voucher export configs

---

mod-finance/mod-finance.postman_collection.json

* Add invoiceId and invoiceLineId to the awaitingPayment schema
* Adjusted awaiting_payment test

MODFIN-113 Add invoiceId and invoiceLineId to the awaitingPayment schema

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-351](https://issues.folio.org/browse/MODORDERS-351)
- added requests for ongoing field validation
folio-testing:

MODORDERS-351 Validate renewal/subscription information

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-342
* added negative test to highlight encumbrance restrictions
Verified on folio-testing

MODORDERS-342 Encumbrance restriction test

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Added API tests to cover https://issues.folio.org/browse/MODKBEKBJ-385 
* added tests for POST /eholdings/resources/bulk/fetch

MODKBEKBJ-385 - Implement endpoint to bulk load resources records

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-341](https://issues.folio.org/browse/MODORDERS-341)
Added following requests to verify that items status is changed correctly if order Closed or Reopend 
folio-testing:

MODORDERS-341 Set item status to "Order closed"

---

mod-invoice/mod-invoice.postman_collection.json

**Purpose:**
Api tests for https://issues.folio.org/browse/MODINVOICE-131
**Purpose:**
- Positive tests for batch-voucher-exports CRUD
- Negative tests for batch-voucher-exports CRUD
Verified in folio-testing:

API tests for MODINVOICE-131 Create batch-voucher-export CRUD API

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-360](https://issues.folio.org/browse/MODORDERS-360)
added tests to verify holdings creation upon check-in for P/E Mix line
folio-testing:

MODORDERS-360 Create holding when receiving a piece and location is changed

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

add tests to cover https://issues.folio.org/browse/MODKBEKBJ-386
Add tests for the following endpoint:
* GET eholdings/packages/bulk/fetch

MODKBEKBJ-386 Add API tests

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-176](https://issues.folio.org/browse/MODORDERS-176)
Adding tests to check creation PO without material types:

[MODORDERS-176] - Failure in inventory interaction, fails the order

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-368
* added check of title.instamceId was updated
* added validation checks if isPackage=true and instanceId specified for poline
Verified on folio SNAPSHOT

MODORDERS-368 implemented instanceId update test

---

mod-orders/mod-orders.postman_collection.json

**Purpose:**
https://issues.folio.org/browse/MODORDERS-345
**Approach:**
- Add positive tests
- Add negative tests
**Verified in folio-snapshot:**

API tests for MODORDERS-345

---

mod-quick-marc/mod-quick-marc.postman_collection.json

[MODQM-9](https://issues.folio.org/browse/MODQM-9) - API Tests for GET /records-editor/records
API test for quickMARC:
Positive test:
1) Get QuickMarcJson record by instanceId - 200 OK
Negative test:
1) Get QuickMarcJson record by instanceId - 404 NOT_FOUND
2) Get QuickMarcJson record by instanceId - 400 BAD_REQUEST
Environment variables are clear:

MODQM-9 - API Tests for GET /records-editor/records

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-109](https://issues.folio.org/browse/MODINVOICE-109)
Adding tests to verify transactions creation upon invoice payment:
- positive 
- negative
folio-testing:
One test is failed due to missing `batch-voucher-storage.export-configurations.item.get` module permission.

MODINVOICE-109 Create payment or credit when Invoice marked as 'Paid'

---

mod-finance/mod-finance.postman_collection.json

[MODFIN-111](https://issues.folio.org/browse/MODFIN-111) - API tests for Exchange rate API
* added positive tests
* added negative tests

MODFIN-111 - API tests for Exchange rate API

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Added API tests for the following endpoints:
* added tests for MODKBEKBJ-408 GET /eholdings/kb-credentials/{credId}/users
* added tests for MODKBEKBJ-410 POST /eholdings/kb-credentials/{credId}/users
* added tests for MODKBEKBJ-411 PUT /eholdings/kb-credentials/{credId}/users/{userId}
* added tests for MODKBEKBJ-412 DELETE /eholdings/kb-credentials/{credId}/users/{userId}

MODKBEKBJ-412 - add api tests for KB Credentials

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-132] - API tests. Batch voucher generation and persistence

[MODINVOICE-132] - API tests. Batch voucher generation and persistence

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Added API tests for the following endpoints:
* added tests for MODKBEKBJ-414 GET /eholdings/kb-credentials/{credId}/custom-labels
* added tests for MODKBEKBJ-415 PUT /eholdings/kb-credentials/{credId}/custom-labels

MODKBEKBJ-415 Add API tests

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-384](https://issues.folio.org/browse/MODORDERS-384)

MODORDERS-384 Item status not set to order closed

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Added API tests for the following endpoints:
* added tests for MODKBEKBJ-424 GET /eholdings/user-kb-credential

MODKBEKBJ-424 API tests

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

API tests for https://issues.folio.org/browse/MODKBEKBJ-416
* added API tests for new endpoint GET /eholdings/kb-credentials/<credentialsId>/proxy-types
* modified existing tests for GET /eholdings/proxy-types

MODKBEKBJ-416 - Update GET /eholdings/proxy-types to support multiple KB credentials

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-383](https://issues.folio.org/browse/MODORDERS-383)
- adding test requests to check ability receive piece if item was deleted
local vagrant box

MODORDERS-383 Can not receive piece when item has been deleted

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Api tests for https://issues.folio.org/browse/MODKBEKBJ-417
* added API test to a new endpoint GET /eholdings/kb-credentials/<credentialsId>/root-proxy

MODKBEKBJ-417 - Update GET /eholdings/root-proxy to support multiple KB credentials

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Api tests for https://issues.folio.org/browse/MODKBEKBJ-418
* updated tests for PUT /eholdings/kb-credentials/<credentialsId>/root-proxy

MODKBEKBJ-418 - Update PUT /eholdings/root-proxy to support multiple KB credentials

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-136 (https://issues.folio.org/browse/MODINVOICE-136 )
- adding tests to check that all fundDistributions in voucherLines have amount type
folio-testing

MODINVOICE-136 Evaluate fund distributions when generating voucher

---

mod-finance/mod-finance.postman_collection.json

Added positive tests:
Added negative tests:

MODFIN-110 - Enforce allocatedFromIds and allocatedToIds

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-336
* added creation of open order for negative tests
* added test for editing poline with inactive access provider

MODORDERS-336 added accessProvider test

---

environment/folio-vagrant.postman_environment
mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Update API test after implementation of MODKBEKBJ-413

MODKBEKBJ-413 Add API tests

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-390] Populate titleId during piece creation

---

mod-finance/mod-finance.postman_collection.json

Tests was changed
Verified on testing

[MODFIN-121] - API tests

---

mod-orders/mod-orders.postman_collection.json

[MODORDERS-359] Support "title" and "package" order lines

---

mod-data-export/mod-data-export.postman_collection.json

Update data export api test to check total number of record

MDEXP-132 Get the total number of records to be exported

---

mod-organizations/mod-organizations.postman_collection.json

API Tests for Organizations API
1) Collection is renamed to mod-organizations
2) Endpoints for organizations CRUD moved to mod-organizations instead of mod-organizations-storage
Verified on localhost:

MODORG-5 - Create business layer proxy API for organization operations 

---

mod-data-export/mod-data-export.postman_collection.json

Create API tests for verifying that default mapping profile exist.

MDEXP-131 Tests for default mapping profile

---

mod-data-export/mod-data-export.postman_collection.json

Create API tests for verifying that default jobprofile exist.

MDEXP-172 API tests for default job profile

---

mod-data-export/mod-data-export.postman_collection.json

MDEXP-171 - Use specified job profile for export process

---

mod-data-export/mod-data-export.postman_collection.json

MDEXP-133 Get the number of already processed records

---

mod-organizations/mod-organizations.postman_collection.json

Added acquisitions units tests:

MODORG-3 API tests

---

mod-organizations/mod-organizations.postman_collection.json

Added acquisitions units test for PUT:

MODORG-4 API tests

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-337
* added unopen tests for negative and positive scenarios
20 failures - out of the scope of this story

MODORDERS-337 added unopen test

---

mod-finance/mod-finance.postman_collection.json

[MODFISTO-90](https://issues.folio.org/browse/MODFISTO-90)
added test to verify that Pending payments handled corectly
updated payment credits tests to check that related pending payments removed when payments and credits are processed
Verified on folio-snapshot
Only tests related to update encumbrances are failing:
Update encumbrance logic is going to be reworked in [MODFISTO-109](https://issues.folio.org/browse/MODFISTO-109)

MODFISTO-90 Support all-or-nothing operations for pending payments by invoice

---

mod-data-export/mod-data-export.postman_collection.json
mod-finance/mod-finance.postman_collection.json

[MODFISTO-90](https://issues.folio.org/browse/MODFISTO-90)
added test to verify that Pending payments handled corectly
updated payment credits tests to check that related pending payments removed when payments and credits are processed
Verified on folio-snapshot
Only tests related to update encumbrances are failing:
Update encumbrance logic is going to be reworked in [MODFISTO-109](https://issues.folio.org/browse/MODFISTO-109)

Modfisto 90

---

mod-orders/mod-orders.postman_collection.json
mod-organizations/mod-organizations.postman_collection.json

[MODORDERS-356] - API tests

---

mod-data-export/mod-data-export.postman_collection.json

MDEXP-175 Validate user info populated for profiles

---

mod-quick-marc/mod-quick-marc.postman_collection.json

HttpStatus 204 changed to 202
Verified on folio-testing

MODQM-19 - quickMARC response status to 202 on record update

---

mod-orders/mod-orders.postman_collection.json

API tests for changes from MODORDERS-335/MODORDERS-397:

MODORDERS-397/MODORDERS-335 

---

mod-data-export/mod-data-export.postman_collection.json

Extend api tests for data export mapping profiles

Extend api tests for data export mapping profiles

---

mod-finance/mod-finance.postman_collection.json

Verified on folio-snapshot:
Two failing tests related to https://issues.folio.org/browse/MODFISTO-114

MODFISTO-109 Api tests

---

mod-organizations/mod-organizations.postman_collection.json

https://issues.folio.org/browse/MODORG-11
Added tests:
Verified on folio-snapshot:

MODORG-11 API tests

---

mod-orders/mod-orders.postman_collection.json

MODORDERS-335 fix failure test cases

---

mod-data-export/mod-data-export.postman_collection.json

MDEXP-186 Check failed export response when file definition not found

---

mod-notes/mod-notes.postman_collection.json

##Purpose
API tests for https://issues.folio.org/browse/MODNOTES-144
##Approach
* updated notes test collection with test for sorting by noteType

MODNOTES-144 - Notes Accordion: Make Note type column heading sortable

---

mod-invoice/mod-invoice.postman_collection.json

https://issues.folio.org/browse/MODINVOICE-172

MODINVOICE-172 added acounting code test

---

mod-notes/mod-notes.postman_collection.json

Api tests for https://issues.folio.org/browse/MODNOTES-146
* updated notes test collection with test for sorting by updatedDate

MODNOTES-146 - Notes Accordion: Make Date column heading sortable

---

mod-orders/mod-orders.postman_collection.json

https://issues.folio.org/browse/MODORDERS-410
Failed test can be skipped

[MODORDERS-410] - API tests

---

mod-finance/mod-finance.postman_collection.json

https://issues.folio.org/browse/MODFIN-134
Replaced `finance-storage/transactions` with `finance/encumbrances` PUT endpoints in encumbrances tests (highlighted):
added negative tests:
Verified on folio-testing environment:

MODFIN-134 API tests

---

mod-finance/mod-finance.postman_collection.json

https://issues.folio.org/browse/MODFIN-131
Changed endpoints to `/finance/pending-payments` in POST requests for `Pending Payments` and `Payments Credits` positive tests:
Added negative test:
Verfied on folio-testing environment:

MODFIN-131 API tests

---

mod-kb-ebsco-java/mod-kb-ebsco-java.postman_collection.json

Update API tests corresponding to MODKBEKBJ-454

MODKBEKBJ-454 Update API tests

---

mod-invoice/mod-invoice.postman_collection.json

[MODINVOICE-105](https://issues.folio.org/browse/MODINVOICE-105)
Fixed prorated adjustment tests
Failing test related to batch-vouchers and going to be moved to [Karate | https://github.com/folio-org/folio-integration-tests]

MODINVOICE-105 Prorated Adjustments - prorating percentage adjustments

---

mod-invoice/mod-invoice.postman_collection.json

Added positive test:
Added negative tests:
1 test relates to batch voucher export. out of scope

MODINVOICE-176 added budget expense class test

---

mod-data-export/mod-data-export.postman_collection.json

MDEXP-194 API tests of associating job profile with job execution 

---

mod-finance/mod-finance.postman_collection.json

MODFIN-138 Update /finance/budgets POST and PUT APIs

---

mod-data-export/mod-data-export.postman_collection.json

MDEXP-150 API test for retrieving transformation fields

---

mod-finance/mod-finance.postman_collection.json

[MODFIN-137](https://issues.folio.org/browse/MODFIN-137)
Verified on folio-snapshot:
Error related to https://issues.folio.org/browse/MODFISTO-103

MODFIN-137 Define and implement GET /finance/groups/id/expense-classes-totals API

---

mod-data-export/mod-data-export.postman_collection.json

https://issues.folio.org/browse/MDEXP-264
Rename all endpoints to follow naming conventions

MDEXP-264: Update endpoint names

---

mod-finance/mod-finance.postman_collection.json

[MODFIN-112](https://issues.folio.org/browse/MODFIN-112)

MODFIN-112 Shouldn't allow negative payments or credits

---

mod-organizations/mod-organizations.postman_collection.json

https://issues.folio.org/browse/MODORGSTOR-83
After updating RMB some checks are failed
updated error messages text

MODORGSTOR-83 fixed tests

---

mod-finance/mod-finance.postman_collection.json

[MODFISTO-142] Update tests for transfer

---

mod-organizations/mod-organizations.postman_collection.json

MODORG-15 fixed tests

---

mod-data-export/mod-data-export.postman_collection.json

MDEXP-282 Add test for /data-export/expire-jobs endpoint

---

mod-invoice/mod-invoice.postman_collection.json

Signed-off-by: Yauheni Kuzmianok <yauheni_kuzmianok@epam.com>

[MODINVOICE-148] Update api tests that have poLine link for invoiceLine

---

mod-invoice/mod-invoice.postman_collection.json

https://issues.folio.org/browse/MODINVOICE-190

MODINVOICE-190 mod-invoice: Update RMB

---

mod-orders/mod-orders.postman_collection.json

[MODORDSTOR-177] - Postman API tests

---

mod-data-export/mod-data-export.postman_collection.json

Modified clean up stage;
Verified on folio-testing env:

MDEXP-259 Add test for error-log endpoint

---

mod-data-export/mod-data-export.postman_collection.json

https://issues.folio.org/browse/MDEXP-276
Fix transformations of custom mapping profile to create mapping profile successfully

MDEXP-276 Fix transformations for mapping profile in api tests

---

mod-data-export/mod-data-export.postman_collection.json

Fix for https://issues.folio.org/browse/MDEXP-292

MDEXP-292 fix API tests for progress.total

---

mod-data-export/mod-data-export.postman_collection.json

**PURPOSE:**
https://issues.folio.org/browse/MDEXP-305
Added test for clean up file definitions endpoint

MDEXP-305 API test for clean up file definitions

---

mod-data-export/mod-data-export.postman_collection.json

MDEXP-285 API test for quick-export

---

mod-finance/mod-finance.postman_collection.json

[MODFISTO-181](https://issues.folio.org/browse/MODFISTO-181) fix clean up

MODFISTO-181 Move allocated logic from trigger to java code

---

mod-gobi/mod-gobi.postman_collection.json

https://issues.folio.org/browse/MODGOBI-100

MODGOBI-100 Update the logic of checking the availability of orders and acq-module
